/* HAVANA NICE — ADMIN CHAT MANAGEMENT V2 */
(() => {
  'use strict';
  if(window.__hnAdminChatV2)return;
  window.__hnAdminChatV2=true;
  const SUPABASE_URL='https://xzfradccsxonmauinecl.supabase.co';
  const SUPABASE_KEY='sb_publishable_Ip5rGK0UVXIfOjs_RQ_LhA_c14foHN9';
  const STYLE_ID='hnAdminChatStyle';
  let sb=null,settings=null,messages=[],channel=null,started=false;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const formatTime=v=>{try{return new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(_){return ''}};
  function style(){if($(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
    .hn-admin-chat-card{grid-column:1/-1}.hn-chat-limit-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hn-chat-limit label{display:block;font-size:8px;letter-spacing:.12em;color:#9b9b96;text-transform:uppercase;margin-bottom:5px}.hn-chat-limit input{width:100%;height:42px}.hn-chat-toolbar{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:18px}.hn-chat-counts{display:flex;gap:7px;flex-wrap:wrap}.hn-chat-stat{border:1px solid #3d321e;padding:8px 10px;font-size:8px;letter-spacing:.12em;color:#9b9b96;text-transform:uppercase}.hn-chat-stat strong{color:#fff1a8;font-size:12px;margin-right:4px}.hn-chat-refresh{height:38px}.hn-chat-bulk{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:12px 0 2px}.hn-chat-bulk button{height:38px;padding:8px 12px}.hn-chat-bulk-status{color:#9b9b96;font-size:8px;letter-spacing:.12em;text-transform:uppercase}.hn-chat-message-list{max-height:650px;overflow:auto}.hn-chat-message{border-top:1px solid #292a27;padding:12px 0;display:flex;gap:12px;align-items:flex-start}.hn-chat-message-check{flex:0 0 auto;padding-top:3px}.hn-chat-message-check input{width:18px;height:18px;accent-color:#e5bd62}.hn-chat-message-main{min-width:0;flex:1}.hn-chat-message-top{display:flex;justify-content:space-between;gap:10px}.hn-chat-message-sender{color:#e5bd62;font-size:9px;letter-spacing:.13em;text-transform:uppercase}.hn-chat-message-time{color:#777;font-size:8px;white-space:nowrap}.hn-chat-message-text{margin-top:5px;color:#f4f1e8;font-size:11px;line-height:1.45;white-space:pre-wrap;overflow-wrap:anywhere}.hn-chat-message-media{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.hn-chat-message-media img,.hn-chat-message-media video{width:78px;height:62px;object-fit:cover;background:#000;border:1px solid #3d321e}.hn-chat-message-actions{flex:0 0 auto}.hn-chat-message-actions button{padding:8px 10px}.hn-chat-audio-admin{margin-top:8px;width:min(100%,360px)}.hn-chat-empty-admin{padding:20px 0;color:#777;font-size:9px;letter-spacing:.12em;text-transform:uppercase;text-align:center}.hn-chat-save{width:100%;margin-top:10px;height:46px}.hn-chat-help{margin-top:7px;color:#777;font-size:8px;line-height:1.45}@media(max-width:600px){.hn-chat-toolbar{align-items:flex-start;flex-direction:column}.hn-chat-message-top{flex-direction:column;gap:3px}}
  `;document.head.appendChild(s)}
  function build(){const dashboard=document.querySelector('.dashboard');if(!dashboard||$('hnAdminChatCard'))return;const card=document.createElement('section');card.className='card hn-admin-chat-card';card.id='hnAdminChatCard';card.innerHTML=`
    <div class="card-head"><div><div class="eyebrow">05 · Comunicación</div><h1>Chat de Información</h1><div class="sub">Control de límites y contenido multimedia</div></div></div>
    <div class="hn-chat-limit-grid"><div class="hn-chat-limit"><label>Máximo de fotos/videos por envío</label><input id="hcMaxMedia" type="number" min="1" max="10" step="1"></div><div class="hn-chat-limit"><label>Máximo de minutos por video</label><input id="hcMaxVideo" type="number" min="1" max="60" step="1"></div></div>
    <button id="hcSave" class="hn-chat-save">Guardar configuración del chat</button><div id="hcMsg" class="msg"></div>
    <div class="hn-chat-toolbar"><div class="hn-chat-counts"><div class="hn-chat-stat"><strong id="hcMessagesCount">0</strong> mensajes</div><div class="hn-chat-stat"><strong id="hcFilesCount">0</strong> archivos</div><div class="hn-chat-stat"><strong id="hcAudioCount">0</strong> audios</div></div><button id="hcRefresh" class="hn-chat-refresh">Actualizar</button></div>
    <div class="hn-chat-bulk"><button id="hcToggleAll">Marcar todos</button><button id="hcDeleteSelected" class="danger">Borrar seleccionados</button><button id="hcDeleteAll" class="danger">Borrar todo</button><span id="hcSelectedStatus" class="hn-chat-bulk-status">0 seleccionados</span></div>
    <div id="hcList" class="hn-chat-message-list"></div>`;
    dashboard.appendChild(card);
    $('hcSave').onclick=saveSettings;$('hcRefresh').onclick=loadMessages;$('hcToggleAll').onclick=toggleAll;$('hcDeleteSelected').onclick=deleteSelected;$('hcDeleteAll').onclick=deleteAll;loadSettings();loadMessages();subscribeRealtime();
  }
  async function getClient(){if(sb)return sb;const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');sb=mod.createClient(SUPABASE_URL,SUPABASE_KEY);window.hnAdminSupabase=sb;return sb}
  async function loadSettings(){try{const c=await getClient(),{data,error}=await c.rpc('admin_get_chat_settings');if(error)throw error;settings=Array.isArray(data)?data[0]:data;if(!settings)throw new Error('Sin configuración');$('hcMaxMedia').value=settings.max_media_files??5;$('hcMaxVideo').value=settings.max_video_minutes??5}catch(e){console.error(e);$('hcMaxMedia').value=5;$('hcMaxVideo').value=5;if($('hcMsg'))$('hcMsg').textContent='No se pudo cargar la configuración'}}
  async function saveSettings(){const maxMedia=Number($('hcMaxMedia').value),maxVideo=Number($('hcMaxVideo').value);if(maxMedia<1||maxMedia>10||maxVideo<1||maxVideo>60){$('hcMsg').textContent='Revisa los límites';return}try{const c=await getClient();const current=settings||{};const{data,error}=await c.rpc('admin_update_chat_settings',{p_background_color:current.background_color||'#020302',p_own_bubble_color:current.own_bubble_color||'#0d5a3d',p_other_bubble_color:current.other_bubble_color||'#171717',p_accent_color:current.accent_color||'#e5bd62',p_text_color:current.text_color||'#f4f1e8',p_max_media_files:maxMedia,p_max_video_minutes:maxVideo});if(error)throw error;settings=Array.isArray(data)?data[0]:data;$('hcMsg').textContent='Configuración guardada';setTimeout(()=>{if($('hcMsg'))$('hcMsg').textContent=''},1800)}catch(e){console.error(e);$('hcMsg').textContent='No se pudo guardar'}}
  async function loadMessages(){try{const c=await getClient(),{data,error}=await c.rpc('admin_list_chat_messages');if(error)throw error;messages=Array.isArray(data)?data:[];renderMessages()}catch(e){console.error(e);if($('hcMsg'))$('hcMsg').textContent='No se pudo cargar el historial'}}
  function selectedIds(){return Array.from($('hcList')?.querySelectorAll('.hn-chat-select:checked')||[]).map(x=>x.value)}
  function updateSelectedStatus(){const n=selectedIds().length;if($('hcSelectedStatus'))$('hcSelectedStatus').textContent=`${n} seleccionados`;if($('hcToggleAll'))$('hcToggleAll').textContent=messages.length&&n===messages.length?'Desmarcar todos':'Marcar todos'}
  function toggleAll(){const checks=Array.from($('hcList')?.querySelectorAll('.hn-chat-select')||[]);const all=checks.length&&checks.every(x=>x.checked);checks.forEach(x=>x.checked=!all);updateSelectedStatus()}
  function renderMessages(){let files=0,audios=0;messages.forEach(m=>{if(m.message_type==='audio')audios++;if(m.message_type==='media')files+=Array.isArray(m.media_urls)?m.media_urls.length:0});$('hcMessagesCount').textContent=messages.length;$('hcFilesCount').textContent=files;$('hcAudioCount').textContent=audios;if(!messages.length){$('hcList').innerHTML='<div class="hn-chat-empty-admin">No hay mensajes en el chat</div>';updateSelectedStatus();return}$('hcList').innerHTML=messages.map(renderMessage).join('');$('hcList').querySelectorAll('[data-delete-chat]').forEach(b=>b.addEventListener('click',()=>deleteMessage(b.dataset.deleteChat)));$('hcList').querySelectorAll('.hn-chat-select').forEach(c=>c.addEventListener('change',updateSelectedStatus));updateSelectedStatus()}
  function renderMessage(m){let media='';if(m.message_type==='media'&&Array.isArray(m.media_urls)){media=`<div class="hn-chat-message-media">${m.media_urls.map((u,i)=>{const t=Array.isArray(m.media_types)?m.media_types[i]:'image';return t==='video'?`<video controls preload="metadata" src="${esc(u)}"></video>`:`<img loading="lazy" src="${esc(u)}" alt="Foto">`}).join('')}</div>`}if(m.message_type==='audio'&&m.audio_url)media=`<audio class="hn-chat-audio-admin" controls preload="metadata" src="${esc(m.audio_url)}"></audio>`;const text=m.message_type==='audio'?'':(m.message||'');return `<div class="hn-chat-message"><div class="hn-chat-message-check"><input class="hn-chat-select" type="checkbox" value="${esc(m.id)}" aria-label="Seleccionar mensaje"></div><div class="hn-chat-message-main"><div class="hn-chat-message-top"><span class="hn-chat-message-sender">${esc(m.sender_name||'MIEMBRO')}</span><span class="hn-chat-message-time">${esc(formatTime(m.created_at))}</span></div>${text?`<div class="hn-chat-message-text">${esc(text)}</div>`:''}${media}</div><div class="hn-chat-message-actions"><button class="danger" data-delete-chat="${esc(m.id)}">Borrar</button></div></div>`}
  async function removeMessageData(c,m){for(const item of mediaItems(m)){try{await c.storage.from(item.bucket).remove([item.path])}catch(e){console.warn('Storage remove',e)}}const{error}=await c.rpc('admin_delete_chat_message',{p_id:m.id});if(error)throw error}
  async function deleteMessage(id){const m=messages.find(x=>String(x.id)===String(id));if(!m||!confirm('¿Borrar este mensaje y sus archivos?'))return;try{const c=await getClient();await removeMessageData(c,m);$('hcMsg').textContent='Mensaje borrado';await loadMessages()}catch(e){console.error(e);$('hcMsg').textContent='No se pudo borrar'}}
  async function deleteSelected(){const ids=selectedIds();const selected=messages.filter(m=>ids.includes(String(m.id)));if(!selected.length)return;if(!confirm(`¿Borrar ${selected.length} mensajes seleccionados y sus archivos?`))return;try{const c=await getClient();$('hcDeleteSelected').disabled=true;for(const m of selected)await removeMessageData(c,m);$('hcMsg').textContent=`${selected.length} mensajes borrados`;await loadMessages()}catch(e){console.error(e);$('hcMsg').textContent='No se pudo completar el borrado seleccionado'}finally{$('hcDeleteSelected').disabled=false}}
  async function deleteAll(){if(!messages.length)return;if(!confirm(`¿Borrar TODOS los ${messages.length} mensajes y sus archivos? Esta acción no se puede deshacer.`))return;try{const c=await getClient();$('hcDeleteAll').disabled=true;for(const m of messages)await removeMessageData(c,m);$('hcMsg').textContent='Todos los mensajes fueron borrados';await loadMessages()}catch(e){console.error(e);$('hcMsg').textContent='No se pudo completar el borrado total'}finally{$('hcDeleteAll').disabled=false}}
  function mediaItems(m){const out=[];const add=(url,bucket)=>{if(!url)return;try{const u=new URL(url);const marker=`/storage/v1/object/public/${bucket}/`;const i=u.pathname.indexOf(marker);if(i>=0)out.push({bucket,path:decodeURIComponent(u.pathname.slice(i+marker.length))})}catch(_){}};if(m.message_type==='audio')add(m.audio_url,'chat-audio');if(m.message_type==='media'&&Array.isArray(m.media_urls))m.media_urls.forEach(u=>add(u,'chat-media'));return out}
  async function subscribeRealtime(){if(channel)return;try{const c=await getClient();channel=c.channel('hn-admin-chat-live').on('postgres_changes',{event:'*',schema:'public',table:'chat_messages'},()=>loadMessages()).subscribe()}catch(e){console.warn('HN admin chat realtime',e)}}
  function waitForAdmin(){if(started)return;const app=$('app'),dashboard=document.querySelector('.dashboard');if(!app||!dashboard){setTimeout(waitForAdmin,250);return}if(app.classList.contains('hidden')){setTimeout(waitForAdmin,400);return}started=true;style();build()}
  waitForAdmin();
})();