/* HAVANA NICE — ADMIN UI V2
   Compact accordion dashboard. Keeps all existing admin logic intact.
*/
(function(){
  'use strict';
  const STYLE_ID='hnAdminUiV1Style';
  const ACC='hn-admin-accordion';
  const summaries={'Accesos a músicos':'Gestiona accesos, activación y músicos','Notificaciones':'Crea y administra avisos para el equipo','Repertorio':'Canciones, idioma y disponibilidad','Calendario de eventos':'Eventos, horarios, vestuario y ubicación','Familia HAVANA NICE':'Controla biografías y fotos de cada perfil','Chat de Información':'Control de límites y contenido multimedia','Resumen':'Estado general de la aplicación'};
  function style(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
    .dashboard{display:flex!important;flex-direction:column!important;gap:10px!important}.dashboard>.card{width:100%;margin:0!important;padding:0!important;overflow:hidden;transition:border-color .2s ease,box-shadow .2s ease}.dashboard>.card.hn-open{box-shadow:0 14px 34px rgba(0,0,0,.25)}.dashboard>.card .card-head{margin:0!important;padding:17px 18px;cursor:pointer;user-select:none;align-items:center!important;min-height:76px}.dashboard>.card .card-head>div:first-child{min-width:0}.dashboard>.card .eyebrow{margin-bottom:5px}.dashboard>.card .card-head h1{font-size:22px!important;line-height:1.15}.dashboard>.card .card-head .sub{font-size:8px;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hn-admin-arrow{width:30px;height:30px;flex:0 0 30px;border:1px solid #70501d;display:flex;align-items:center;justify-content:center;color:#e5bd62;font-size:15px;transition:transform .2s ease,background .2s ease}.hn-open .hn-admin-arrow{transform:rotate(180deg);background:rgba(229,189,98,.06)}.hn-admin-body{padding:0 18px 18px}.hn-admin-body>*:first-child{margin-top:0}.hn-admin-collapsible{display:none!important}.hn-open .hn-admin-collapsible{display:block!important}.hn-family-card{border-color:rgba(229,189,98,.48)!important}.hn-family-card .hn-admin-body{min-height:54px}.hn-family-placeholder{padding:10px 0;color:#777;font-size:9px;letter-spacing:.14em;text-transform:uppercase}.hn-summary-card,.hn-access-card,.hn-admin-chat-card{border-color:rgba(130,190,145,.38)!important;background:linear-gradient(145deg,#0a1b12,#07100b)!important;box-shadow:0 14px 34px rgba(0,0,0,.24)}.hn-summary-card .stat{border-color:rgba(130,190,145,.20);background:rgba(0,0,0,.18)}
    .hn-admin-chat-card .card-head{background:linear-gradient(90deg,rgba(18,96,61,.18),rgba(0,0,0,0))!important}.hn-admin-chat-card .eyebrow{color:#79b894!important}.hn-admin-chat-card .sub{color:#8da79a!important}.hn-admin-chat-card .hn-chat-stat{border-color:rgba(54,180,112,.28)!important}.hn-admin-chat-card .hn-chat-stat strong{color:#9be0b4!important}
    #songList .song{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:14px!important;min-height:54px;padding:13px 0!important;margin:0!important;border-top:1px solid #292a27!important}#songList .song-fields{display:block!important;min-width:0!important;flex:1!important}#songList .song-fields input,#songList .song-fields select{display:none!important}#songList .song-fields .hn-song-display{display:block!important;min-width:0}#songList .hn-song-title{font-size:10px!important;letter-spacing:.1em!important;text-transform:uppercase!important;color:#f4f1e8!important;line-height:1.35!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis}#songList .hn-song-artist{font-size:9px!important;color:#9b9b96!important;margin-top:4px!important;line-height:1.35!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis}#songList .song-actions{display:flex!important;gap:6px!important;flex-shrink:0!important}#songList .song-actions button{min-width:74px!important;height:34px!important;padding:8px 10px!important}#songList .song.hn-song-editing .song-fields input,#songList .song.hn-song-editing .song-fields select{display:block!important;width:100%!important;margin-bottom:7px!important}#songList .song.hn-song-editing .song-fields .hn-song-display{display:none!important}
    @media(max-width:760px){.dashboard>.card .card-head{padding:15px 16px;min-height:70px}.dashboard>.card .card-head h1{font-size:20px!important}.hn-admin-body{padding:0 16px 16px}#songList .song{gap:9px!important}#songList .song-actions button{min-width:68px!important;padding:8px 7px!important}}
  `;document.head.appendChild(s)}
  function findCard(titleText){return [...document.querySelectorAll('.dashboard>.card')].find(card=>card.querySelector('.card-head h1')?.textContent.trim()===titleText)||null}
  function ensureFamilyCard(){const dashboard=document.querySelector('.dashboard');if(!dashboard||document.getElementById('hnAdminFamilyCard'))return;const card=document.createElement('section');card.className='card hn-family-card';card.id='hnAdminFamilyCard';card.innerHTML=`<div class="card-head"><div><div class="eyebrow">05 · Familia</div><h1>Familia HAVANA NICE</h1><div class="sub">Controla biografías y fotos de cada perfil</div></div></div><div class="hn-family-placeholder">Cargando familia…</div>`;dashboard.appendChild(card)}
  function arrange(){const dashboard=document.querySelector('.dashboard');if(!dashboard)return;const desired=['Calendario de eventos','Repertorio','Notificaciones','Familia HAVANA NICE','Chat de Información','Accesos a músicos','Resumen'];const cards=desired.map(findCard).filter(Boolean);const current=[...dashboard.children].map(card=>card.querySelector('.card-head h1')?.textContent.trim()).filter(Boolean);const target=cards.map(card=>card.querySelector('.card-head h1')?.textContent.trim());if(current.join('\u0000')===target.join('\u0000'))return;cards.forEach(card=>dashboard.appendChild(card))}
  function enhance(card){if(!card||card.dataset.hnAccordion==='1')return;const head=card.querySelector(':scope > .card-head');if(!head)return;card.dataset.hnAccordion='1';const title=head.querySelector('h1'),sub=head.querySelector('.sub');if(title&&summaries[title.textContent.trim()]&&sub)sub.textContent=summaries[title.textContent.trim()];const arrow=document.createElement('div');arrow.className='hn-admin-arrow';arrow.setAttribute('aria-hidden','true');arrow.textContent='⌄';head.appendChild(arrow);const body=document.createElement('div');body.className='hn-admin-body hn-admin-collapsible';Array.from(card.children).filter(x=>x!==head).forEach(x=>body.appendChild(x));card.appendChild(body);const toggle=()=>{const open=!card.classList.contains('hn-open');card.classList.toggle('hn-open',open);head.setAttribute('aria-expanded',String(open))};head.setAttribute('role','button');head.setAttribute('tabindex','0');head.setAttribute('aria-expanded','false');head.addEventListener('click',toggle);head.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})}
  function normalizeRepertoireSelect(select){if(!select)return;const current=String(select.value||'').toUpperCase();select.innerHTML='<option value="ENGLISH">ENGLISH</option><option value="ESPAÑOL">ESPAÑOL</option>';select.value=current==='ESPAÑOL'?'ESPAÑOL':'ENGLISH'}
  function normalizeRepertoireControls(){const add=document.getElementById('songCategory');if(add)normalizeRepertoireSelect(add);document.querySelectorAll('.edit-category').forEach(normalizeRepertoireSelect)}
  function decorateSong(song){if(!song)return;const fields=song.querySelector('.song-fields');if(!fields)return;let display=fields.querySelector('.hn-song-display');if(!display){display=document.createElement('div');display.className='hn-song-display';fields.appendChild(display)}const inputs=fields.querySelectorAll('input');const title=inputs[0]?.value||'';const artist=inputs[1]?.value||'';if(display.dataset.title!==title||display.dataset.artist!==artist){display.dataset.title=title;display.dataset.artist=artist;display.innerHTML=`<div class="hn-song-title"></div><div class="hn-song-artist"></div>`;display.querySelector('.hn-song-title').textContent=title;display.querySelector('.hn-song-artist').textContent=artist}const action=song.querySelector('.song-actions button:first-child');if(action&&!action.dataset.hnEditBound){action.dataset.hnEditBound='1';action.textContent='EDITAR';action.addEventListener('click',function(e){if(!song.classList.contains('hn-song-editing')){e.preventDefault();e.stopImmediatePropagation();song.classList.add('hn-song-editing');action.textContent='GUARDAR';inputs[0]?.focus();}},true)}}
  function scanRepertoire(){normalizeRepertoireControls();document.querySelectorAll('#songList .song').forEach(decorateSong)}
  function scan(){ensureFamilyCard();scanSummary();scanAccess();scanRepertoire();document.querySelectorAll('.dashboard>.card').forEach(enhance);arrange()}
  function scanSummary(){const summary=findCard('Resumen');if(summary)summary.classList.add('hn-summary-card')}
  function scanAccess(){const access=findCard('Accesos a músicos');if(access)access.classList.add('hn-access-card')}
  function init(){style();scan();loadScript('hnAdminChatScript','./admin-chat-v1.js?v=8259b6335a4e8b8f937b51ad550694d6cfd0a236');loadScript('hnCalendarRecipientsScript','./calendar-recipients-v1.js?v=a6e80f29a5ed64be9f164c7dfe88f27d737e416c');loadScript('hnAdminSummaryRealtime','./admin-summary-realtime.js?v=fdcd0cdb498b007e9841e854ea3cd0d840368016');loadScript('hnAdminStorageSummary','./admin-storage-summary.js?v=196dc5c8bb70d6507fd0cb58949c8a70dd8f1785');loadScript('hnAdminBackground','./admin-background-v1.js?v=ac202c1acdfda3f1197b68a9a944905725dda210');loadScript('hnAdminDeviceAccess','./admin-access-v1.js?v=1d3804774cfce3eb66127b6d173d3f0d35401e37');loadScript('hnAdminChatLightboxV2','./chat-media-lightbox-v2.js?v=8653eb4f9a04346a99c88632fff36b10875f5150');loadScript('hnAdminFamily','./admin-family-v1.js?v=9abc141b29b92071ddacd08ddc2ccb9011b75c7b');const root=document.querySelector('.dashboard');if(root){const observer=new MutationObserver(()=>{observer.disconnect();scan();observer.observe(root,{childList:true,subtree:true})});observer.observe(root,{childList:true,subtree:true})}}
  function loadScript(id,src){if(document.getElementById(id))return;const script=document.createElement('script');script.id=id;script.src=src;document.body.appendChild(script)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
