/* HAVANA NICE — ADMIN UI V2
   Compact accordion dashboard. Keeps all existing admin logic intact.
*/
(function(){
  'use strict';
  const STYLE_ID='hnAdminUiV1Style';
  const ACC='hn-admin-accordion';
  const summaries={'Accesos a músicos':'Gestiona accesos, activación y músicos','Notificaciones':'Crea y administra avisos para el equipo','Repertorio':'Canciones, categorías y disponibilidad','Calendario de eventos':'Eventos, horarios, vestuario y ubicación','Familia HAVANA NICE':'Espacio reservado para la familia HAVANA NICE','Chat de Información':'Control de límites y contenido multimedia','Resumen':'Estado general de la aplicación'};
  function style(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
    .dashboard{display:flex!important;flex-direction:column!important;gap:10px!important}.dashboard>.card{width:100%;margin:0!important;padding:0!important;overflow:hidden;transition:border-color .2s ease,box-shadow .2s ease}.dashboard>.card.hn-open{box-shadow:0 14px 34px rgba(0,0,0,.25)}.dashboard>.card .card-head{margin:0!important;padding:17px 18px;cursor:pointer;user-select:none;align-items:center!important;min-height:76px}.dashboard>.card .card-head>div:first-child{min-width:0}.dashboard>.card .eyebrow{margin-bottom:5px}.dashboard>.card .card-head h1{font-size:22px!important;line-height:1.15}.dashboard>.card .card-head .sub{font-size:8px;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hn-admin-arrow{width:30px;height:30px;flex:0 0 30px;border:1px solid #70501d;display:flex;align-items:center;justify-content:center;color:#e5bd62;font-size:15px;transition:transform .2s ease,background .2s ease}.hn-open .hn-admin-arrow{transform:rotate(180deg);background:rgba(229,189,98,.06)}.hn-admin-body{padding:0 18px 18px}.hn-admin-body>*:first-child{margin-top:0}.hn-admin-collapsible{display:none!important}.hn-open .hn-admin-collapsible{display:block!important}.hn-family-card{border-color:rgba(229,189,98,.48)!important}.hn-family-card .hn-admin-body{min-height:54px}.hn-family-placeholder{padding:10px 0;color:#777;font-size:9px;letter-spacing:.14em;text-transform:uppercase}.hn-summary-card,.hn-access-card{border-color:rgba(130,190,145,.38)!important;background:linear-gradient(145deg,#0a1b12,#07100b)!important;box-shadow:0 14px 34px rgba(0,0,0,.24)}.hn-summary-card .stat{border-color:rgba(130,190,98,.20);background:rgba(0,0,0,.18)}
    @media(max-width:760px){.dashboard>.card .card-head{padding:15px 16px;min-height:70px}.dashboard>.card .card-head h1{font-size:20px!important}.hn-admin-body{padding:0 16px 16px}}
  `;document.head.appendChild(s)}
  function findCard(titleText){return [...document.querySelectorAll('.dashboard>.card')].find(card=>card.querySelector('.card-head h1')?.textContent.trim()===titleText)||null}
  function ensureFamilyCard(){const dashboard=document.querySelector('.dashboard');if(!dashboard||document.getElementById('hnAdminFamilyCard'))return;const card=document.createElement('section');card.className='card hn-family-card';card.id='hnAdminFamilyCard';card.innerHTML=`<div class="card-head"><div><div class="eyebrow">05 · Familia</div><h1>Familia HAVANA NICE</h1><div class="sub">Espacio para la familia HAVANA NICE</div></div></div><div class="hn-family-placeholder">Próximamente</div>`;dashboard.appendChild(card)}
  function arrange(){const dashboard=document.querySelector('.dashboard');if(!dashboard)return;const desired=['Calendario de eventos','Repertorio','Notificaciones','Familia HAVANA NICE','Chat de Información','Accesos a músicos','Resumen'];const cards=desired.map(findCard).filter(Boolean);const current=[...dashboard.children].map(card=>card.querySelector('.card-head h1')?.textContent.trim()).filter(Boolean);const target=cards.map(card=>card.querySelector('.card-head h1')?.textContent.trim());if(current.join('\u0000')===target.join('\u0000'))return;cards.forEach(card=>dashboard.appendChild(card))}
  function enhance(card){if(!card||card.dataset.hnAccordion==='1')return;const head=card.querySelector(':scope > .card-head');if(!head)return;card.dataset.hnAccordion='1';const title=head.querySelector('h1'),sub=head.querySelector('.sub');if(title&&summaries[title.textContent.trim()]&&sub)sub.textContent=summaries[title.textContent.trim()];const arrow=document.createElement('div');arrow.className='hn-admin-arrow';arrow.setAttribute('aria-hidden','true');arrow.textContent='⌄';head.appendChild(arrow);const body=document.createElement('div');body.className='hn-admin-body hn-admin-collapsible';Array.from(card.children).filter(x=>x!==head).forEach(x=>body.appendChild(x));card.appendChild(body);head.setAttribute('role','button');head.setAttribute('tabindex','0');head.setAttribute('aria-expanded','false');const toggle=()=>{const open=!card.classList.contains('hn-open');card.classList.toggle('hn-open',open);head.setAttribute('aria-expanded',String(open))};head.addEventListener('click',toggle);head.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})}
  function scan(){ensureFamilyCard();scanSummary();scanAccess();document.querySelectorAll('.dashboard>.card').forEach(enhance);arrange()}
  function scanSummary(){const summary=findCard('Resumen');if(summary)summary.classList.add('hn-summary-card')}
  function scanAccess(){const access=findCard('Accesos a músicos');if(access)access.classList.add('hn-access-card')}
  function init(){style();scan();loadScript('hnAdminChatScript','./admin-chat-v1.js?v=b0d5e9c9d956d219e4a64338904eb65bf9060da3');loadScript('hnCalendarRecipientsScript','./calendar-recipients-v1.js?v=a6e80f29a5ed64be9f164c7dfe88f27d737e416c');loadScript('hnAdminSummaryRealtime','./'+'admin-summary-realtime.js?v=92b964be8321e152e68acf479fa3ec6dd6590152');const root=document.querySelector('.dashboard');if(root)new MutationObserver(scan).observe(root,{childList:true,subtree:true})}
  function loadScript(id,src){if(document.getElementById(id))return;const script=document.createElement('script');script.id=id;script.src=src;document.body.appendChild(script)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
