/* HAVANA NICE — CHAT DE INFORMACIÓN / REAL TIME V7 */
(() => {
  'use strict';

  const CHAT_TABLE = 'chat_messages';
  const AUDIO_BUCKET = 'chat-audio';
  const MEDIA_BUCKET = 'chat-media';
  const SETTINGS_RPC = 'get_chat_settings';
  const MAX_LENGTH = 1000;
  const MAX_MEDIA = 5;
  const MAX_VIDEO_SECONDS = 5 * 60;
  const READ_KEY = 'hn_chat_last_read_at';

  let chatChannel = null, messages = [], chatScreen = null, listEl = null;
  let inputEl = null, sendEl = null, micEl = null, mediaEl = null;
  let initialized = false, replyTarget = null, historyArmed = false;
  let previousScreen = null, videoWasMuted = true;
  let mediaRecorder = null, audioChunks = [], recordingStartedAt = 0, recordingTimer = null;
  let pendingVoice = null, pendingMedia = [], pendingPreviewUrls = [];
  let chatReconnectTimer = null, chatReconnectDelay = 1000;
  let chatSettings = {max_media_files: MAX_MEDIA, max_video_minutes: 5};

  const esc = value => String(value ?? '').replace(/[&<>'\"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch]));
  const session = () => { try { return JSON.parse(sessionStorage.getItem('hn_profile') || 'null'); } catch (_) { return null; } };
  const client = () => window.hnSupabase || window.hnMusicianSupabase || window.supabaseClient || window.supabase || null;
  const currentProfile = () => { const p = session(); return p && p.id ? p : null; };
  const readKey = () => `${READ_KEY}:${currentProfile()?.id || 'anonymous'}`;
  const formatTime = ts => { try { return new Intl.DateTimeFormat('es-MX',{hour:'2-digit',minute:'2-digit'}).format(new Date(ts)); } catch (_) { return ''; } };
  const formatDuration = seconds => { const total=Math.max(0,Math.floor(Number(seconds)||0)); return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`; };
  const dayLabel = ts => { const d=new Date(ts), now=new Date(); const same=(a,b)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate(); if(same(d,now))return 'HOY'; const y=new Date(now);y.setDate(now.getDate()-1);if(same(d,y))return 'AYER';return new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'short',year:'numeric'}).format(d).toUpperCase(); };

  function parseLegacyReply(value) {
    const raw=String(value??'');
    if(!raw.startsWith('↳ ')) return {quote:null,text:raw};
    const i=raw.indexOf('\n---\n');
    if(i<0) return {quote:null,text:raw};
    const q=raw.slice(2,i), t=raw.slice(i+5), c=q.indexOf(': ');
    return {quote:c>=0?{sender:q.slice(0,c),text:q.slice(c+2)}:{sender:'MIEMBRO',text:q},text:t};
  }

  function getReplyTarget(message) {
    if(message?.reply_to_message_id) return messages.find(m => String(m.id)===String(message.reply_to_message_id)) || null;
    return null;
  }

  function replyPreview(message) {
    if(!message) return '';
    if(message.message_type==='audio') return '🎙 NOTA DE VOZ';
    if(message.message_type==='media') return message.message ? message.message.slice(0,160) : '📎 FOTOS / VIDEOS';
    return String(message.message||'').slice(0,160);
  }

  function ensureHomeModule(){
    const modules=document.querySelector('.modules'); if(!modules)return null;
    let existing=[...modules.querySelectorAll('.module')].find(el=>/CHAT DE INFORMACIÓN|CHAT DE INFORMACION/i.test(el.textContent||''));
    if(!existing){existing=document.createElement('button');existing.type='button';existing.className='module hn-chat-module';existing.innerHTML='<span class="module-number">05</span><span class="module-copy"><span class="module-title">CHAT DE INFORMACIÓN</span><span class="module-subtitle">MENSAJES DEL EQUIPO</span></span><span class="module-arrow">›</span>';const family=[...modules.querySelectorAll('.module')].find(el=>/FAMILIA/i.test(el.textContent||''));if(family&&family.nextSibling)modules.insertBefore(existing,family.nextSibling);else modules.appendChild(existing);}
    return existing;
  }

  function ensureStyles(){
    let style=document.getElementById('hn-chat-styles');if(!style){style=document.createElement('style');style.id='hn-chat-styles';document.head.appendChild(style);}
    style.textContent=`
      .hn-chat-module{position:relative!important;background:linear-gradient(145deg,#0b1710,#08110c)!important;border-color:rgba(229,189,98,.30)!important;box-shadow:0 6px 18px rgba(0,0,0,.14)}
      .hn-chat-module:hover{background:linear-gradient(145deg,#102017,#0c160f)!important;border-color:rgba(229,189,98,.46)!important}
      .hn-chat-screen{padding-bottom:max(24px,env(safe-area-inset-bottom))}.hn-chat-screen.is-active~.controls{display:none!important}.experience:has(#hn-chat-screen.is-active) .controls{display:none!important}
      .hn-chat-wrap{width:min(100%,720px);height:100%;margin:0 auto;display:flex;flex-direction:column;min-height:0}.hn-chat-head{flex:0 0 auto;text-align:center;padding:4px 0 18px}.hn-chat-head-title{margin:0;font-family:Georgia,"Times New Roman",serif;font-size:clamp(25px,7vw,38px);font-weight:400;letter-spacing:.04em;text-transform:uppercase}.hn-chat-head-sub{margin:9px 0 0;color:rgba(244,241,232,.44);font-size:8px;letter-spacing:.22em;text-transform:uppercase}
      .hn-chat-list{flex:1 1 auto;min-height:0;overflow-y:auto;overscroll-behavior:contain;padding:4px 2px 18px;scrollbar-width:none}.hn-chat-list::-webkit-scrollbar{display:none}.hn-chat-day{text-align:center;margin:13px 0 10px;color:rgba(244,241,232,.30);font-size:8px;letter-spacing:.22em}.hn-chat-row{display:flex;margin:7px 0}.hn-chat-row.mine{justify-content:flex-end}.hn-chat-bubble{max-width:min(88%,560px);padding:10px 12px 8px;border:1px solid rgba(229,189,98,.22);background:#151a17!important;backdrop-filter:blur(7px);cursor:pointer;touch-action:pan-y;user-select:none}.hn-chat-row.mine .hn-chat-bubble{border-color:#d9b45f!important;background:#173a2b!important;box-shadow:inset 0 0 0 1px rgba(255,241,168,.05),0 4px 18px rgba(0,0,0,.12)}.hn-chat-bubble.hn-chat-selected{border-color:#f3d77c!important;box-shadow:0 0 0 1px rgba(229,189,98,.35),0 0 18px rgba(229,189,98,.1)}
      .hn-chat-sender{margin-bottom:5px;color:#d9b45f;font-size:8px;font-weight:500;letter-spacing:.16em;text-transform:uppercase}.hn-chat-text{color:#eee9df;font-size:14px;line-height:1.42;white-space:pre-wrap;overflow-wrap:anywhere;user-select:text}.hn-chat-time{margin-top:5px;color:rgba(244,241,232,.34);font-size:8px;text-align:right;letter-spacing:.08em}.hn-chat-quoted{margin-bottom:8px;padding:7px 9px;border-left:2px solid #d9b45f;background:rgba(229,189,98,.05)}.hn-chat-quoted-sender{color:#d9b45f;font-size:8px;font-weight:500;letter-spacing:.12em;text-transform:uppercase;margin-bottom:3px}.hn-chat-quoted-text{color:rgba(244,241,232,.52);font-size:11px;line-height:1.3;white-space:pre-wrap;overflow:hidden;max-height:42px}
      .hn-chat-audio-label{display:flex;align-items:center;gap:8px;color:#eee9df;font-size:11px;letter-spacing:.1em;text-transform:uppercase;margin-bottom:7px}.hn-chat-audio-icon{color:#d9b45f;font-size:17px;line-height:1}.hn-chat-audio-player{width:min(100%,360px);display:flex;align-items:center;gap:9px}.hn-chat-audio-play{width:40px;height:40px;flex:0 0 40px;border:1px solid rgba(229,189,98,.50);border-radius:50%;background:rgba(0,0,0,.26);color:#f3d77c;display:flex;align-items:center;justify-content:center;font-size:17px;line-height:1;padding:0}.hn-chat-audio-progress{flex:1;min-width:50px;height:4px;appearance:none;-webkit-appearance:none;background:rgba(244,241,232,.16);accent-color:#d9b45f}.hn-chat-audio-duration{min-width:40px;color:rgba(244,241,232,.54);font-size:9px;font-variant-numeric:tabular-nums;text-align:right}.hn-chat-audio-native{display:none}
      .hn-chat-media-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px;margin-top:3px}.hn-chat-media-item{position:relative;overflow:hidden;background:#090909;border:1px solid rgba(229,189,98,.14);min-height:100px}.hn-chat-media-item img,.hn-chat-media-item video{width:100%;height:100%;display:block;object-fit:cover;max-height:260px}.hn-chat-media-item video{background:#000}.hn-chat-photo-button{display:block;width:100%;height:100%;padding:0;border:0;background:transparent;cursor:zoom-in}.hn-chat-photo-button img{width:100%;height:100%;display:block;object-fit:cover;max-height:260px}.hn-chat-bubble:has(.hn-chat-media-grid){padding:4px;width:fit-content;max-width:min(88%,560px)}.hn-chat-media-grid:has(> .hn-chat-media-item:only-child){display:block;width:fit-content;max-width:100%}.hn-chat-media-grid:has(> .hn-chat-media-item:only-child) .hn-chat-media-item{display:block;width:fit-content;min-height:0;max-width:100%;height:auto}.hn-chat-media-grid .hn-chat-media-item img,.hn-chat-media-grid .hn-chat-media-item video{width:auto;height:auto;max-width:100%;max-height:260px;object-fit:contain}.hn-chat-media-grid:has(> .hn-chat-media-item:only-child) .hn-chat-photo-button{width:auto;height:auto;max-width:100%}.hn-chat-media-grid:has(> .hn-chat-media-item:only-child) .hn-chat-photo-button img{width:auto;height:auto;max-width:100%;max-height:260px;object-fit:contain}
      .hn-chat-reply{flex:0 0 auto;display:none;align-items:stretch;border-top:1px solid rgba(229,189,98,.13);background:rgba(0,0,0,.18)}.hn-chat-reply.is-visible{display:flex}.hn-chat-reply-line{width:2px;flex:0 0 2px;background:#d9b45f}.hn-chat-reply-copy{flex:1;min-width:0;padding:8px 10px}.hn-chat-reply-label{color:#d9b45f;font-size:8px;font-weight:500;letter-spacing:.16em;text-transform:uppercase}.hn-chat-reply-text{margin-top:4px;color:rgba(244,241,232,.6);font-size:11px;line-height:1.3;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hn-chat-reply-close{width:42px;border:0;background:transparent;color:rgba(244,241,232,.6);font-size:18px}
      .hn-chat-compose{flex:0 0 auto;display:flex;flex-direction:column;gap:8px;padding-top:8px;border-top:1px solid rgba(229,189,98,.13)}.hn-chat-input-wrap{position:relative;width:100%}.hn-chat-input{width:100%;min-width:0;min-height:78px;max-height:150px;resize:none;box-sizing:border-box;padding:14px 106px 14px 12px;border:1px solid rgba(229,189,98,.34);border-radius:0;outline:none;background:rgba(0,0,0,.34);color:#eee9df;font-size:14px;line-height:1.4}.hn-chat-input::placeholder{color:rgba(244,241,232,.30)}.hn-chat-mic,.hn-chat-attach{position:absolute;bottom:9px;width:42px;height:42px;border:1px solid rgba(229,189,98,.50);border-radius:50%;background:rgba(0,0,0,.46);color:#d9b45f;display:flex;align-items:center;justify-content:center;font-size:20px;line-height:1}.hn-chat-mic{right:9px}.hn-chat-attach{right:58px;font-size:19px}.hn-chat-mic.is-recording{border-color:#f3d77c;background:#6d1515;color:#f3d77c;animation:hnChatPulse 1.15s ease-in-out infinite}.hn-chat-mic:disabled,.hn-chat-attach:disabled{opacity:.45}.hn-chat-recording{display:none;align-items:center;justify-content:space-between;min-height:42px;padding:0 12px;border:1px solid rgba(229,189,98,.35);background:rgba(0,0,0,.34);color:#eee9df}.hn-chat-recording.is-visible{display:flex}.hn-chat-recording.is-pending{border-color:#d9b45f}.hn-chat-recording-status{color:#d9b45f;font-size:9px;font-weight:500;letter-spacing:.15em;text-transform:uppercase}.hn-chat-recording-time{font-variant-numeric:tabular-nums;font-size:13px;letter-spacing:.08em}.hn-chat-media-pending{display:none;gap:7px;overflow-x:auto;padding:4px 0}.hn-chat-media-pending.is-visible{display:flex}.hn-chat-pending-item{position:relative;width:72px;height:72px;flex:0 0 72px;border:1px solid rgba(229,189,98,.34);overflow:hidden;background:#111}.hn-chat-pending-item img,.hn-chat-pending-item video{width:100%;height:100%;object-fit:cover}.hn-chat-pending-remove{position:absolute;top:3px;right:3px;width:22px;height:22px;border:1px solid #d9b45f;border-radius:50%;background:#111;color:#fff;font-size:14px;line-height:18px;padding:0}.hn-chat-send{width:100%;min-height:52px;border:1px solid #d9b45f;border-radius:0;background:rgba(0,0,0,.35);color:#f3d77c;font-size:10px;font-weight:500;letter-spacing:.16em;text-transform:uppercase}.hn-chat-send:disabled{opacity:.4}.hn-chat-empty{padding:45px 20px;text-align:center;color:rgba(244,241,232,.38);font-size:10px;letter-spacing:.18em;text-transform:uppercase}
      @keyframes hnChatPulse{0%,100%{box-shadow:0 0 0 0 rgba(243,215,124,0)}50%{box-shadow:0 0 0 6px rgba(243,215,124,.08)}}
    `;
  }

  async function loadChatSettings(){
    const sb=client();
    if(!sb)return;
    try{
      const {data,error}=await sb.rpc(SETTINGS_RPC);
      if(error)throw error;
      const row=Array.isArray(data)?data[0]:data;
      if(!row)return;
      chatSettings={max_media_files:Math.min(10,Math.max(1,Number(row.max_media_files)||MAX_MEDIA)),max_video_minutes:Math.min(60,Math.max(1,Number(row.max_video_minutes)||5))};
    }catch(error){console.warn('HAVANA NICE chat settings load failed:',error);}
  }

  function buildScreen(){
    if(chatScreen){wireModule();return;}
    chatScreen=document.createElement('section');chatScreen.id='hn-chat-screen';chatScreen.className='screen hn-chat-screen';chatScreen.setAttribute('aria-label','Chat de información');
    chatScreen.innerHTML=`<div class="hn-chat-wrap"><header class="hn-chat-head"><h1 class="hn-chat-head-title">CHAT DE INFORMACIÓN</h1><p class="hn-chat-head-sub">MENSAJES DEL EQUIPO</p></header><div class="hn-chat-list" aria-live="polite"></div><div class="hn-chat-reply"><div class="hn-chat-reply-line"></div><div class="hn-chat-reply-copy"><div class="hn-chat-reply-label"></div><div class="hn-chat-reply-text"></div></div><button class="hn-chat-reply-close" type="button" aria-label="Cancelar respuesta">×</button></div><form class="hn-chat-compose"><div class="hn-chat-input-wrap"><textarea class="hn-chat-input" maxlength="1000" placeholder="ESCRIBE UN MENSAJE" aria-label="Mensaje"></textarea><button class="hn-chat-attach" type="button" aria-label="Adjuntar fotos o videos">＋</button><button class="hn-chat-mic" type="button" aria-label="Grabar nota de voz">◉</button><input class="hn-chat-media-input" type="file" accept="image/*,video/*" multiple hidden></div><div class="hn-chat-media-pending"></div><div class="hn-chat-recording"><span class="hn-chat-recording-status">GRABANDO</span><span class="hn-chat-recording-time">00:00</span></div><button class="hn-chat-send" type="submit">ENVIAR</button></form></div>`;
    document.querySelector('.experience')?.appendChild(chatScreen);listEl=chatScreen.querySelector('.hn-chat-list');inputEl=chatScreen.querySelector('.hn-chat-input');sendEl=chatScreen.querySelector('.hn-chat-send');micEl=chatScreen.querySelector('.hn-chat-mic');mediaEl=chatScreen.querySelector('.hn-chat-media-input');
    chatScreen.querySelector('.hn-chat-reply-close').addEventListener('click',closeReply);chatScreen.querySelector('.hn-chat-compose').addEventListener('submit',sendMessage);micEl.addEventListener('click',toggleRecording);chatScreen.querySelector('.hn-chat-attach').addEventListener('click',()=>mediaEl.click());mediaEl.addEventListener('change',e=>handleMediaFiles(e.target.files));inputEl.addEventListener('input',()=>{inputEl.style.height='auto';inputEl.style.height=Math.min(inputEl.scrollHeight,150)+'px';updateSendState();});
    ensureStyles();wireModule();subscribe();loadMessages();loadChatSettings();
  }

  function scrollToLatest(){
    if(!listEl||!chatScreen?.classList.contains('is-active'))return;
    const move=()=>{try{listEl.scrollTop=listEl.scrollHeight;}catch(_){}};
    requestAnimationFrame(()=>{move();requestAnimationFrame(move);});
    [80,250,600].forEach(delay=>setTimeout(move,delay));
    listEl.querySelectorAll('img,video').forEach(media=>{
      const event=media.tagName==='IMG'?'load':'loadedmetadata';
      if((media.tagName==='IMG'&&media.complete)||(media.tagName==='VIDEO'&&media.readyState>=1))return;
      media.addEventListener(event,move,{once:true});
    });
  }

  function render(forceBottom=false){
    if(!listEl)return;
    if(!messages.length){listEl.innerHTML='<div class="hn-chat-empty">AÚN NO HAY MENSAJES</div>';return;}
    const frag=document.createDocumentFragment();let lastDay='';
    messages.forEach(message=>{
      const day=dayLabel(message.created_at);if(day!==lastDay){const d=document.createElement('div');d.className='hn-chat-day';d.textContent=day;frag.appendChild(d);lastDay=day;}
      const row=document.createElement('div');const mine=String(message.profile_id)===String(currentProfile()?.id||'');row.className='hn-chat-row'+(mine?' mine':'');
      const bubble=document.createElement('div');bubble.className='hn-chat-bubble';bubble.dataset.messageId=message.id;
      const reply=getReplyTarget(message);let body='';if(reply)body+=`<div class="hn-chat-quoted"><div class="hn-chat-quoted-sender">${esc(reply.sender_name||'MIEMBRO')}</div><div class="hn-chat-quoted-text">${esc(replyPreview(reply))}</div></div>`;
      if(message.message_type==='audio'&&message.audio_url){body+=`<div class="hn-chat-audio-label"><span class="hn-chat-audio-icon">◉</span><span>NOTA DE VOZ</span></div><div class="hn-chat-audio-player"><button class="hn-chat-audio-play" type="button" aria-label="Reproducir nota de voz">▶</button><input class="hn-chat-audio-progress" type="range" min="0" max="100" value="0" aria-label="Progreso del audio"><span class="hn-chat-audio-duration">00:00 / ${formatDuration(message.audio_duration)}</span><audio class="hn-chat-audio-native" preload="metadata" src="${esc(message.audio_url)}"></audio></div>`;}else if(message.message_type==='media'&&Array.isArray(message.media_urls)){body+=`<div class="hn-chat-media-grid">${message.media_urls.map((url,i)=>{const type=message.media_types?.[i]||'';return `<div class="hn-chat-media-item">${type.startsWith('image/')?`<button class="hn-chat-photo-button" type="button" data-photo-url="${esc(url)}"><img src="${esc(url)}" alt="Foto compartida" loading="lazy"></button>`:`<video src="${esc(url)}" controls playsinline preload="metadata"></video>`}</div>`;}).join('')}</div>`;}else{body+=`<div class="hn-chat-text">${esc(message.message||'')}</div>`;}
      body+=`<div class="hn-chat-time">${esc(message.sender_name||'MIEMBRO')} · ${formatTime(message.created_at)}</div>`;bubble.innerHTML=body;row.appendChild(bubble);frag.appendChild(row);
    });
    const nearBottom=listEl.scrollHeight-listEl.scrollTop-listEl.clientHeight<120;listEl.replaceChildren(frag);wireMessageInteractions();if(forceBottom||nearBottom)scrollToLatest();
  }

  function wireMessageInteractions(){
    if(!listEl)return;
    listEl.querySelectorAll('.hn-chat-bubble').forEach(bubble=>{bubble.addEventListener('click',e=>{if(e.target.closest('audio,video,button,input'))return;if(bubble.dataset.hnSwiped==='1'){bubble.dataset.hnSwiped='0';return;}selectMessage(bubble.dataset.messageId);});let startX=0,startY=0,tracking=false;bubble.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;startX=e.clientX;startY=e.clientY;tracking=true;try{bubble.setPointerCapture(e.pointerId);}catch(_){}});bubble.addEventListener('pointermove',e=>{if(!tracking)return;const dx=e.clientX-startX,dy=e.clientY-startY;if(dx>12&&Math.abs(dx)>Math.abs(dy))bubble.style.transform=`translateX(${Math.min(dx,72)}px)`});const finish=e=>{if(!tracking)return;const dx=e.clientX-startX,dy=e.clientY-startY;tracking=false;bubble.style.transform='';if(dx>=55&&Math.abs(dx)>Math.abs(dy)*1.15){bubble.dataset.hnSwiped='1';selectMessage(bubble.dataset.messageId);}};bubble.addEventListener('pointerup',finish);bubble.addEventListener('pointercancel',()=>{tracking=false;bubble.style.transform='';});});
    listEl.querySelectorAll('.hn-chat-photo-button').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();if(window.hnOpenChatMedia)window.hnOpenChatMedia(btn.dataset.photoUrl,'image');}));
    listEl.querySelectorAll('.hn-chat-audio-player').forEach(box=>{const audio=box.querySelector('audio'),play=box.querySelector('.hn-chat-audio-play'),bar=box.querySelector('.hn-chat-audio-progress'),duration=box.querySelector('.hn-chat-audio-duration');if(!audio||!play)return;const refresh=()=>{const dur=audio.duration||Number(audio.dataset.duration)||0;if(bar)bar.value=dur?(audio.currentTime/dur)*100:0;if(duration)duration.textContent=`${formatDuration(audio.currentTime)} / ${formatDuration(dur)}`;play.textContent=audio.paused?'▶':'❚❚';};play.addEventListener('click',e=>{e.stopPropagation();if(audio.paused)audio.play().catch(()=>{});else audio.pause();});audio.addEventListener('timeupdate',refresh);audio.addEventListener('loadedmetadata',refresh);audio.addEventListener('ended',refresh);bar?.addEventListener('input',e=>{e.stopPropagation();if(audio.duration)audio.currentTime=(Number(bar.value)/100)*audio.duration;});refresh();});
  }

  function pickAudioMime(){if(!window.MediaRecorder)return '';return ['audio/mp4;codecs=mp4a.40.2','audio/mp4','audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t))||'';}
  function updateRecordingUI(){const box=chatScreen?.querySelector('.hn-chat-recording'),time=chatScreen?.querySelector('.hn-chat-recording-time');if(!box||!time)return;box.classList.add('is-visible');time.textContent=formatDuration((Date.now()-recordingStartedAt)/1000);}
  function stopRecordingTimer(){if(recordingTimer)clearInterval(recordingTimer);recordingTimer=null;}
  function resetRecordingUI(pending=false){stopRecordingTimer();const box=chatScreen?.querySelector('.hn-chat-recording'),time=chatScreen?.querySelector('.hn-chat-recording-time');if(box)box.classList.toggle('is-visible',pending);if(box)box.classList.toggle('is-pending',pending);if(time&&!pending)time.textContent='00:00';micEl?.classList.remove('is-recording');micEl?.setAttribute('aria-label','Grabar nota de voz');micEl?.setAttribute('title','Grabar nota de voz');if(pending){const status=chatScreen?.querySelector('.hn-chat-recording-status');if(status)status.textContent='NOTA DE VOZ LISTA';if(time)time.textContent=formatDuration(pendingVoice?.duration||0);}}
  function startRecording(){if(pendingMedia.length){alert('Primero envía o elimina las fotos/videos seleccionados.');return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){alert('Este dispositivo o navegador no permite grabar notas de voz.');return;}const mimeType=pickAudioMime();navigator.mediaDevices.getUserMedia({audio:true}).then(stream=>{audioChunks=[];mediaRecorder=mimeType?new MediaRecorder(stream,{mimeType}):new MediaRecorder(stream);recordingStartedAt=Date.now();micEl?.classList.add('is-recording');micEl?.setAttribute('aria-label','Detener grabación');micEl?.setAttribute('title','Detener grabación');updateRecordingUI();recordingTimer=setInterval(updateRecordingUI,250);mediaRecorder.ondataavailable=e=>{if(e.data?.size)audioChunks.push(e.data)};mediaRecorder.onerror=()=>{stream.getTracks().forEach(t=>t.stop());mediaRecorder=null;resetRecordingUI(false);alert('No se pudo grabar el audio.');};mediaRecorder.onstop=()=>{stopRecordingTimer();stream.getTracks().forEach(t=>t.stop());const duration=Math.max(1,Math.round((Date.now()-recordingStartedAt)/1000));const blob=new Blob(audioChunks,{type:mediaRecorder?.mimeType||mimeType||'audio/webm'});mediaRecorder=null;if(!blob.size)return;pendingVoice={blob,duration};resetRecordingUI(true);updateSendState();inputEl?.focus();};mediaRecorder.start();}).catch(error=>{console.error('HAVANA NICE microphone permission failed:',error);alert('Necesitamos permiso para usar el micrófono.');});}
  function stopRecording(){if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();}
  function toggleRecording(){if(micEl?.disabled)return;if(mediaRecorder&&mediaRecorder.state==='recording')stopRecording();else startRecording();}
  function getVideoDuration(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),video=document.createElement('video');video.preload='metadata';video.onloadedmetadata=()=>{const d=Number(video.duration)||0;URL.revokeObjectURL(url);resolve(d)};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('No se pudo leer el video.'))};video.src=url;});}
  async function handleMediaFiles(fileList){const files=[...fileList];if(!files.length)return;if(pendingVoice){pendingVoice=null;resetRecordingUI(false);}const maxMedia=Math.min(10,Math.max(1,Number(chatSettings.max_media_files)||MAX_MEDIA));if(pendingMedia.length+files.length>maxMedia){alert(`Puedes subir máximo ${maxMedia} fotos/videos por envío.`);mediaEl.value='';return;}for(const file of files){if(!file.type.startsWith('image/')&&!file.type.startsWith('video/')){alert('Solo puedes subir fotos o videos.');continue;}if(file.type.startsWith('video/')){try{const duration=await getVideoDuration(file);const maxSeconds=Math.min(60,Math.max(1,Number(chatSettings.max_video_minutes)||5))*60;if(!duration||duration>maxSeconds){alert(`El video "${file.name}" supera el máximo de ${Math.round(maxSeconds/60)} minutos.`);continue;}}catch(_){alert(`No se pudo revisar el video "${file.name}".`);continue;}}pendingMedia.push(file);}mediaEl.value='';renderPendingMedia();updateSendState();}
  function clearPendingPreviewUrls(){pendingPreviewUrls.forEach(url=>{try{URL.revokeObjectURL(url)}catch(_){}});pendingPreviewUrls=[];}
  function renderPendingMedia(){const box=chatScreen?.querySelector('.hn-chat-media-pending');if(!box)return;clearPendingPreviewUrls();if(!pendingMedia.length){box.classList.remove('is-visible');box.innerHTML='';return;}box.classList.add('is-visible');box.innerHTML=pendingMedia.map((file,i)=>{const url=URL.createObjectURL(file);pendingPreviewUrls.push(url);const tag=file.type.startsWith('video/')?'video':'img';return `<div class="hn-chat-pending-item"><${tag} src="${url}" ${tag==='video'?'muted':''}></${tag}><button class="hn-chat-pending-remove" type="button" data-index="${i}" aria-label="Eliminar archivo">×</button></div>`;}).join('');box.querySelectorAll('.hn-chat-pending-remove').forEach(btn=>btn.addEventListener('click',()=>{pendingMedia.splice(Number(btn.dataset.index),1);renderPendingMedia();updateSendState();}));}

  async function removeUploadedObjects(sb,bucket,paths){if(!sb||!paths?.length)return;try{const result=await sb.storage.from(bucket).remove(paths);if(result?.error)throw result.error;}catch(error){console.warn('HAVANA NICE orphan cleanup failed:',error);}}
  async function uploadVoiceNote(blob,duration){const sb=client(),p=currentProfile();if(!sb||!p?.id)throw new Error('Sesión no disponible.');const ext=blob.type.includes('mp4')?'m4a':blob.type.includes('ogg')?'ogg':'webm';const path=`${p.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from(AUDIO_BUCKET).upload(path,blob,{contentType:blob.type||'audio/webm',upsert:false});if(up.error)throw up.error;try{const {data}=sb.storage.from(AUDIO_BUCKET).getPublicUrl(path);const ins=await sb.from(CHAT_TABLE).insert({profile_id:p.id,sender_name:p.username||'MIEMBRO',message:'',message_type:'audio',audio_url:data.publicUrl,audio_duration:duration});if(ins.error)throw ins.error;}catch(error){await removeUploadedObjects(sb,AUDIO_BUCKET,[path]);throw error;}}
  async function uploadMedia(){const sb=client(),p=currentProfile();if(!sb||!p?.id||!pendingMedia.length)return;const urls=[],types=[],paths=[];try{for(const file of pendingMedia){const ext=(file.name.split('.').pop()||'bin').toLowerCase(),path=`${p.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from(MEDIA_BUCKET).upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(up.error)throw up.error;paths.push(path);const {data}=sb.storage.from(MEDIA_BUCKET).getPublicUrl(path);urls.push(data.publicUrl);types.push(file.type||'');}const ins=await sb.from(CHAT_TABLE).insert({profile_id:p.id,sender_name:p.username||'MIEMBRO',message:'',message_type:'media',media_urls:urls,media_types:types});if(ins.error)throw ins.error;pendingMedia=[];clearPendingPreviewUrls();renderPendingMedia();}catch(error){await removeUploadedObjects(sb,MEDIA_BUCKET,paths);throw error;}}
  function updateSendState(){if(!sendEl)return;sendEl.disabled=!!mediaRecorder||(!String(inputEl?.value||'').trim()&&!pendingVoice&&!pendingMedia.length);}
  async function sendMessage(e){e.preventDefault();if(mediaRecorder&&mediaRecorder.state==='recording')return;const sb=client(),p=currentProfile();if(!sb||!p?.id)return;sendEl.disabled=true;try{if(pendingVoice){const voice=pendingVoice;pendingVoice=null;await uploadVoiceNote(voice.blob,voice.duration);inputEl.value='';inputEl.style.height='auto';closeReply();resetRecordingUI(false);return;}if(pendingMedia.length){await uploadMedia();inputEl.value='';inputEl.style.height='auto';closeReply();return;}const text=String(inputEl.value||'').trim();if(!text)return;const payload={profile_id:p.id,sender_name:p.username||'MIEMBRO',message:text.slice(0,MAX_LENGTH),message_type:'text'};if(replyTarget?.id)payload.reply_to_message_id=replyTarget.id;const ins=await sb.from(CHAT_TABLE).insert(payload);if(ins.error)throw ins.error;inputEl.value='';inputEl.style.height='auto';closeReply();}catch(error){console.error('HAVANA NICE chat send failed:',error);alert(error?.message||'No se pudo enviar.');}finally{updateSendState();inputEl?.focus();}}

  function updateUnread(){const module=ensureHomeModule();if(!module)return;const last=localStorage.getItem(readKey()),lastTime=last?Date.parse(last):NaN,count=Number.isNaN(lastTime)?messages.length:messages.filter(m=>Date.parse(m.created_at)>lastTime).length;let badge=module.querySelector('.hn-chat-unread');if(count<=0){if(badge)badge.remove();return;}if(!badge){badge=document.createElement('span');badge.className='hn-chat-unread';badge.style.cssText='position:absolute;top:10px;right:48px;min-width:19px;height:19px;padding:0 5px;border-radius:12px;display:flex;align-items:center;justify-content:center;background:#d9b45f;color:#020302;font-size:9px;font-weight:700;';module.appendChild(badge);}badge.textContent=count>99?'99+':String(count);badge.hidden=false;}
  function markRead(){try{localStorage.setItem(readKey(),new Date().toISOString());}catch(_){}updateUnread();}
  async function loadMessages(){const sb=client();if(!sb)return;const {data,error}=await sb.from(CHAT_TABLE).select('id,profile_id,sender_name,message,created_at,message_type,audio_url,audio_duration,media_urls,media_types,reply_to_message_id').order('created_at',{ascending:true}).limit(200);if(error){console.warn('HAVANA NICE chat load failed:',error);return;}messages=data||[];render(!!chatScreen?.classList.contains('is-active'));updateUnread();}
  window.hnChatReconcile=()=>loadMessages();
  function subscribe(){const sb=client();if(!sb)return;clearTimeout(chatReconnectTimer);if(chatChannel){try{sb.removeChannel(chatChannel);}catch(_){}chatChannel=null;}chatChannel=sb.channel('hn-chat-realtime').on('postgres_changes',{event:'INSERT',schema:'public',table:CHAT_TABLE},payload=>{const row=payload.new;if(!messages.some(m=>String(m.id)===String(row.id))){messages.push(row);messages.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));render(true);}if(chatScreen?.classList.contains('is-active'))markRead();else updateUnread();}).on('postgres_changes',{event:'DELETE',schema:'public',table:CHAT_TABLE},payload=>{const id=payload.old?.id;if(!id)return;const had=messages.some(m=>String(m.id)===String(id));messages=messages.filter(m=>String(m.id)!==String(id));if(replyTarget?.id===id)closeReply();if(had)render();else updateUnread();}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'chat_settings'},()=>{loadChatSettings();}).subscribe(status=>{if(status==='SUBSCRIBED'){chatReconnectDelay=1000;clearTimeout(chatReconnectTimer);}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){clearTimeout(chatReconnectTimer);chatReconnectTimer=setTimeout(()=>subscribe(),chatReconnectDelay);chatReconnectDelay=Math.min(chatReconnectDelay*2,10000);}});}
  function closeReply(){replyTarget=null;chatScreen?.querySelector('.hn-chat-reply')?.classList.remove('is-visible');chatScreen?.querySelectorAll('.hn-chat-bubble.hn-chat-selected').forEach(el=>el.classList.remove('hn-chat-selected'));}
  function selectMessage(id){const message=messages.find(m=>String(m.id)===String(id));if(!message)return;replyTarget=message;chatScreen?.querySelectorAll('.hn-chat-bubble').forEach(el=>el.classList.toggle('hn-chat-selected',el.dataset.messageId===String(id)));const reply=chatScreen?.querySelector('.hn-chat-reply');if(reply){reply.classList.add('is-visible');const who=reply.querySelector('.hn-chat-reply-label'),text=reply.querySelector('.hn-chat-reply-text');if(who)who.textContent=`RESPONDER A ${message.sender_name||'MIEMBRO'}`;if(text)text.textContent=replyPreview(message);}inputEl?.focus();}
  function closeChat(fromButton=false){if(!chatScreen)return;if(mediaRecorder&&mediaRecorder.state==='recording'){try{mediaRecorder.stop();}catch(_){} }closeReply();chatScreen.classList.remove('is-active');if(previousScreen)previousScreen.classList.add('is-active');else document.getElementById('homeScreen')?.classList.add('is-active');const video=document.getElementById('backgroundVideo');if(video)video.muted=videoWasMuted;if(historyArmed&&fromButton){historyArmed=false;try{history.back();}catch(_){}}else if(!fromButton)historyArmed=false;}
  function openChat(fromPopState=false){buildScreen();previousScreen=document.querySelector('.screen.is-active:not(#hn-chat-screen)')||document.getElementById('homeScreen');document.querySelectorAll('.screen').forEach(s=>{if(s!==chatScreen)s.classList.remove('is-active')});chatScreen.classList.add('is-active');markRead();render(true);const video=document.getElementById('backgroundVideo');if(video){videoWasMuted=!!video.muted;video.muted=true;video.play().catch(()=>{});}if(!fromPopState&&!historyArmed){try{history.pushState({...history.state,hnChat:true},'',location.href);historyArmed=true;}catch(_){}}setTimeout(()=>inputEl?.focus(),250);}
  function wireModule(){const module=ensureHomeModule();if(!module||module.dataset.hnChatBound==='1')return;module.dataset.hnChatBound='1';module.addEventListener('click',()=>openChat());}
  window.addEventListener('popstate',e=>{if(historyArmed){historyArmed=false;closeChat(false);}});
  const observer=new MutationObserver(()=>wireModule());observer.observe(document.documentElement,{childList:true,subtree:true});
  function init(){if(initialized)return;initialized=true;ensureStyles();wireModule();window.addEventListener('hn:session-ready',()=>{subscribe();loadMessages();loadChatSettings();});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();