/* HAVANA NICE — CHAT DE INFORMACIÓN / REAL TIME V3 */
(() => {
  'use strict';

  const SUPABASE_URL = 'https://xzfradccsxonmauinecl.supabase.co';
  const CHAT_TABLE = 'chat_messages';
  const AUDIO_BUCKET = 'chat-audio';
  const MEDIA_BUCKET = 'chat-media';
  const MAX_LENGTH = 1000;
  const MAX_MEDIA = 5;
  const MAX_VIDEO_SECONDS = 5 * 60;
  const READ_KEY = 'hn_chat_last_read_at';
  const REPLY_SEPARATOR = '\n---\n';

  let chatChannel = null, messages = [], chatScreen = null, listEl = null;
  let inputEl = null, sendEl = null, micEl = null, mediaEl = null;
  let initialized = false, replyTarget = null, historyArmed = false;
  let previousScreen = null, videoWasMuted = true;
  let mediaRecorder = null, audioChunks = [], recordingStartedAt = 0, recordingTimer = null;
  let pendingVoice = null;
  let pendingMedia = [];
  let lightboxEl = null, lightboxHistory = false;

  const esc = value => String(value ?? '').replace(/[&<>'\"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch]));
  const session = () => { try { return JSON.parse(sessionStorage.getItem('hn_profile') || 'null'); } catch (_) { return null; } };
  const client = () => window.hnSupabase || window.supabaseClient || window.supabase || null;
  const currentProfile = () => { const p = session(); return p && p.id ? p : null; };
  const readKey = () => `${READ_KEY}:${currentProfile()?.id || 'anonymous'}`;
  const formatTime = ts => { try { return new Intl.DateTimeFormat('es-MX',{hour:'2-digit',minute:'2-digit'}).format(new Date(ts)); } catch (_) { return ''; } };
  const formatDuration = seconds => { const total=Math.max(0,Math.floor(Number(seconds)||0)); return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`; };
  const dayLabel = ts => { const d=new Date(ts), now=new Date(); const same=(a,b)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate(); if(same(d,now))return 'HOY'; const y=new Date(now);y.setDate(now.getDate()-1);if(same(d,y))return 'AYER';return new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'short',year:'numeric'}).format(d).toUpperCase(); };

  function parseReplyMessage(value) {
    const raw=String(value??''); if(!raw.startsWith('↳ '))return {quote:null,text:raw};
    const i=raw.indexOf(REPLY_SEPARATOR); if(i>=0){const q=raw.slice(2,i),t=raw.slice(i+REPLY_SEPARATOR.length),c=q.indexOf(': ');return {quote:c>=0?{sender:q.slice(0,c),text:q.slice(c+2)}:{sender:'MIEMBRO',text:q},text:t};}
    const i2=raw.indexOf('\n'); if(i2>=0){const q=raw.slice(2,i2),t=raw.slice(i2+1),c=q.indexOf(': ');return {quote:c>=0?{sender:q.slice(0,c),text:q.slice(c+2)}:{sender:'MIEMBRO',text:q},text:t};}
    return {quote:null,text:raw};
  }

  function ensureHomeModule(){
    const modules=document.querySelector('.modules'); if(!modules)return null;
    let existing=[...modules.querySelectorAll('.module')].find(el=>/CHAT DE INFORMACIÓN|CHAT DE INFORMACION/i.test(el.textContent||''));
    if(!existing){existing=document.createElement('button');existing.type='button';existing.className='module hn-chat-module';existing.innerHTML='<span class="module-number">05</span><span class="module-copy"><span class="module-title">CHAT DE INFORMACIÓN</span><span class="module-subtitle">MENSAJES DEL EQUIPO</span></span><span class="module-arrow">›</span>';const family=[...modules.querySelectorAll('.module')].find(el=>/FAMILIA/i.test(el.textContent||''));if(family&&family.nextSibling)modules.insertBefore(existing,family.nextSibling);else modules.appendChild(existing);}
    return existing;
  }

  function ensureStyles(){
    let style=document.getElementById('hn-chat-styles');if(!style){style=document.createElement('style');style.id='hn-chat-styles';document.head.appendChild(style);}
    style.textContent=`
      .hn-chat-module{position:relative}.hn-chat-screen{padding-bottom:max(24px,env(safe-area-inset-bottom))}.hn-chat-screen.is-active~.controls{display:none!important}.experience:has(#hn-chat-screen.is-active) .controls{display:none!important}
      .hn-chat-wrap{width:min(100%,720px);height:100%;margin:0 auto;display:flex;flex-direction:column;min-height:0}.hn-chat-head{flex:0 0 auto;text-align:center;padding:4px 0 18px}.hn-chat-head-title{margin:0;font-family:Georgia,"Times New Roman",serif;font-size:clamp(25px,7vw,38px);font-weight:400;letter-spacing:.04em;text-transform:uppercase}.hn-chat-head-sub{margin:9px 0 0;color:rgba(244,241,232,.48);font-size:8px;letter-spacing:.22em;text-transform:uppercase}
      .hn-chat-list{flex:1 1 auto;min-height:0;overflow-y:auto;overscroll-behavior:contain;padding:4px 2px 18px;scrollbar-width:none}.hn-chat-list::-webkit-scrollbar{display:none}.hn-chat-day{text-align:center;margin:13px 0 10px;color:rgba(244,241,232,.35);font-size:8px;letter-spacing:.22em}.hn-chat-row{display:flex;margin:7px 0}.hn-chat-row.mine{justify-content:flex-end}.hn-chat-bubble{max-width:min(88%,560px);padding:10px 12px 8px;border:1px solid rgba(229,189,98,.32);background:#171717!important;backdrop-filter:blur(7px);cursor:pointer;touch-action:pan-y;user-select:none}.hn-chat-row.mine .hn-chat-bubble{border-color:#e5bd62!important;background:#0d5a3d!important;box-shadow:inset 0 0 0 1px rgba(255,241,168,.1),0 4px 18px rgba(0,0,0,.2)}.hn-chat-bubble.hn-chat-selected{border-color:#fff1a8!important;box-shadow:0 0 0 1px rgba(229,189,98,.35),0 0 18px rgba(229,189,98,.1)}.hn-chat-sender{margin-bottom:5px;color:#e5bd62;font-size:8px;font-weight:600;letter-spacing:.16em;text-transform:uppercase}.hn-chat-text{color:#f4f1e8;font-size:14px;line-height:1.42;white-space:pre-wrap;overflow-wrap:anywhere;user-select:text}.hn-chat-time{margin-top:5px;color:rgba(244,241,232,.42);font-size:8px;text-align:right;letter-spacing:.08em}.hn-chat-quoted{margin-bottom:8px;padding:7px 9px;border-left:2px solid #e5bd62;background:rgba(229,189,98,.08)}.hn-chat-quoted-sender{color:#e5bd62;font-size:8px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;margin-bottom:3px}.hn-chat-quoted-text{color:rgba(244,241,232,.58);font-size:11px;line-height:1.3;white-space:pre-wrap;overflow:hidden;max-height:42px}
      .hn-chat-audio-label{display:flex;align-items:center;gap:8px;color:#f4f1e8;font-size:11px;letter-spacing:.1em;text-transform:uppercase;margin-bottom:7px}.hn-chat-audio-icon{color:#e5bd62;font-size:17px;line-height:1}.hn-chat-audio-player{width:min(100%,360px);display:flex;align-items:center;gap:9px}.hn-chat-audio-play{width:40px;height:40px;flex:0 0 40px;border:1px solid rgba(229,189,98,.65);border-radius:50%;background:rgba(0,0,0,.32);color:#fff1a8;display:flex;align-items:center;justify-content:center;font-size:17px;line-height:1;padding:0}.hn-chat-audio-progress{flex:1;min-width:50px;height:4px;appearance:none;-webkit-appearance:none;background:rgba(244,241,232,.2);accent-color:#e5bd62}.hn-chat-audio-duration{min-width:40px;color:rgba(244,241,232,.62);font-size:9px;font-variant-numeric:tabular-nums;text-align:right}.hn-chat-audio-native{display:none}
      .hn-chat-media-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px;margin-top:3px}.hn-chat-media-item{position:relative;overflow:hidden;background:#090909;border:1px solid rgba(229,189,98,.2);min-height:100px}.hn-chat-media-item img,.hn-chat-media-item video{width:100%;height:100%;display:block;object-fit:cover;max-height:260px}.hn-chat-media-item video{background:#000}.hn-chat-media-item video::-webkit-media-controls-overflow-button{display:none!important}.hn-chat-photo-button{display:block;width:100%;height:100%;padding:0;border:0;background:transparent;cursor:zoom-in}.hn-chat-photo-button img{width:100%;height:100%;display:block;object-fit:cover;max-height:260px}
      .hn-chat-lightbox{position:fixed;inset:0;z-index:100000;display:none;align-items:center;justify-content:center;padding:20px;box-sizing:border-box;background:rgba(0,0,0,.94);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px)}.hn-chat-lightbox.is-open{display:flex}.hn-chat-lightbox-image{display:block;max-width:96vw;max-height:88vh;width:auto;height:auto;object-fit:contain;box-shadow:0 12px 50px rgba(0,0,0,.6)}.hn-chat-lightbox-close{position:absolute;top:max(16px,env(safe-area-inset-top));right:16px;width:46px;height:46px;border:1px solid rgba(229,189,98,.7);border-radius:50%;background:rgba(0,0,0,.55);color:#fff1a8;font-size:28px;line-height:1;display:flex;align-items:center;justify-content:center}.hn-chat-lightbox-hint{position:absolute;bottom:max(16px,env(safe-area-inset-bottom));left:0;right:0;text-align:center;color:rgba(244,241,232,.45);font-size:8px;letter-spacing:.18em;text-transform:uppercase}
      .hn-chat-media-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px;margin-top:3px}.hn-chat-media-item{position:relative;overflow:hidden;background:#090909;border:1px solid rgba(229,189,98,.2);min-height:100px}.hn-chat-media-item img,.hn-chat-media-item video{width:100%;height:100%;display:block;object-fit:cover;max-height:260px}.hn-chat-media-item video{background:#000}
      .hn-chat-reply{flex:0 0 auto;display:none;align-items:stretch;border-top:1px solid rgba(229,189,98,.18);background:rgba(0,0,0,.22)}.hn-chat-reply.is-visible{display:flex}.hn-chat-reply-line{width:2px;flex:0 0 2px;background:#e5bd62}.hn-chat-reply-copy{flex:1;min-width:0;padding:8px 10px}.hn-chat-reply-label{color:#e5bd62;font-size:8px;font-weight:600;letter-spacing:.16em;text-transform:uppercase}.hn-chat-reply-text{margin-top:4px;color:rgba(244,241,232,.6);font-size:11px;line-height:1.3;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hn-chat-reply-close{width:42px;border:0;background:transparent;color:rgba(244,241,232,.6);font-size:18px}
      .hn-chat-compose{flex:0 0 auto;display:flex;flex-direction:column;gap:8px;padding-top:8px;border-top:1px solid rgba(229,189,98,.18)}.hn-chat-input-wrap{position:relative;width:100%}.hn-chat-input{width:100%;min-width:0;min-height:78px;max-height:150px;resize:none;box-sizing:border-box;padding:14px 106px 14px 12px;border:1px solid rgba(229,189,98,.45);border-radius:0;outline:none;background:rgba(0,0,0,.42);color:#f4f1e8;font-size:14px;line-height:1.4}.hn-chat-input::placeholder{color:rgba(244,241,232,.35)}.hn-chat-mic,.hn-chat-attach{position:absolute;bottom:9px;width:42px;height:42px;border:1px solid rgba(229,189,98,.65);border-radius:50%;background:rgba(0,0,0,.55);color:#e5bd62;display:flex;align-items:center;justify-content:center;font-size:20px;line-height:1}.hn-chat-mic{right:9px}.hn-chat-attach{right:58px;font-size:19px}.hn-chat-mic.is-recording{border-color:#fff1a8;background:#6d1515;color:#fff1a8;animation:hnChatPulse 1.15s ease-in-out infinite}.hn-chat-mic:disabled,.hn-chat-attach:disabled{opacity:.45}.hn-chat-recording{display:none;align-items:center;justify-content:space-between;min-height:42px;padding:0 12px;border:1px solid rgba(229,189,98,.35);background:rgba(0,0,0,.42);color:#f4f1e8}.hn-chat-recording.is-visible{display:flex}.hn-chat-recording.is-pending{border-color:#e5bd62}.hn-chat-recording-status{color:#e5bd62;font-size:9px;font-weight:600;letter-spacing:.15em;text-transform:uppercase}.hn-chat-recording-time{font-variant-numeric:tabular-nums;font-size:13px;letter-spacing:.08em}.hn-chat-media-pending{display:none;gap:7px;overflow-x:auto;padding:4px 0}.hn-chat-media-pending.is-visible{display:flex}.hn-chat-pending-item{position:relative;width:72px;height:72px;flex:0 0 72px;border:1px solid rgba(229,189,98,.45);overflow:hidden;background:#111}.hn-chat-pending-item img,.hn-chat-pending-item video{width:100%;height:100%;object-fit:cover}.hn-chat-pending-remove{position:absolute;top:3px;right:3px;width:22px;height:22px;border:1px solid #e5bd62;border-radius:50%;background:#111;color:#fff;font-size:14px;line-height:18px;padding:0}.hn-chat-send{width:100%;min-height:52px;border:1px solid #e5bd62;border-radius:0;background:rgba(0,0,0,.35);color:#fff1a8;font-size:10px;font-weight:600;letter-spacing:.16em;text-transform:uppercase}.hn-chat-send:disabled{opacity:.4}.hn-chat-empty{padding:45px 20px;text-align:center;color:rgba(244,241,232,.38);font-size:9px;letter-spacing:.18em;text-transform:uppercase}@keyframes hnChatPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.08)}}
    `;
  }

  function buildLightbox(){
    if(lightboxEl)return lightboxEl;
    lightboxEl=document.createElement('div');
    lightboxEl.className='hn-chat-lightbox';
    lightboxEl.innerHTML='<button class="hn-chat-lightbox-close" type="button" aria-label="Cerrar foto">×</button><img class="hn-chat-lightbox-image" alt="Foto ampliada"><div class="hn-chat-lightbox-hint">TOCA FUERA DE LA FOTO PARA CERRAR</div>';
    document.body.appendChild(lightboxEl);
    const image=lightboxEl.querySelector('.hn-chat-lightbox-image');
    lightboxEl.addEventListener('click',e=>{if(e.target===lightboxEl)closeLightbox();});
    lightboxEl.querySelector('.hn-chat-lightbox-close').addEventListener('click',closeLightbox);
    image.addEventListener('click',e=>e.stopPropagation());
    return lightboxEl;
  }
  function openLightbox(url){
    if(!url)return;const box=buildLightbox(),image=box.querySelector('.hn-chat-lightbox-image');image.src=url;box.classList.add('is-open');
    if(!lightboxHistory){try{history.pushState({...history.state,hnChat:true,hnLightbox:true},'',location.href);lightboxHistory=true;}catch(_) {}}
  }
  function closeLightbox(fromPopState=false){
    if(!lightboxEl?.classList.contains('is-open'))return;
    lightboxEl.classList.remove('is-open');const image=lightboxEl.querySelector('.hn-chat-lightbox-image');if(image)image.removeAttribute('src');
    if(lightboxHistory){lightboxHistory=false;if(!fromPopState){try{history.back();}catch(_){}}}
  }

  function closeReply(){replyTarget=null;chatScreen?.querySelector('.hn-chat-reply')?.classList.remove('is-visible');chatScreen?.querySelectorAll('.hn-chat-bubble.hn-chat-selected').forEach(el=>el.classList.remove('hn-chat-selected'));}
  function selectMessage(id){const message=messages.find(m=>m.id===id);if(!message)return;replyTarget=message;chatScreen?.querySelectorAll('.hn-chat-bubble').forEach(el=>el.classList.toggle('hn-chat-selected',el.dataset.messageId===id));const parsed=parseReplyMessage(message.message);const reply=chatScreen?.querySelector('.hn-chat-reply');if(reply){reply.classList.add('is-visible');const who=reply.querySelector('.hn-chat-reply-label'),text=reply.querySelector('.hn-chat-reply-text');if(who)who.textContent=`RESPONDER A ${message.sender_name||'MIEMBRO'}`;if(text)text.textContent=message.message_type==='audio'?'🎙 NOTA DE VOZ':message.message_type==='media'?'📎 FOTOS / VIDEOS':(parsed.text||message.message||'');}inputEl?.focus();}

  function wireMessageInteractions(){
    if(!listEl)return;listEl.querySelectorAll('.hn-chat-bubble').forEach(bubble=>{bubble.addEventListener('click',e=>{if(e.target.closest('audio,video,button,input'))return;if(bubble.dataset.hnSwiped==='1'){bubble.dataset.hnSwiped='0';return;}selectMessage(bubble.dataset.messageId);});let startX=0,startY=0,tracking=false;bubble.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;startX=e.clientX;startY=e.clientY;tracking=true;try{bubble.setPointerCapture(e.pointerId);}catch(_){}});bubble.addEventListener('pointermove',e=>{if(!tracking)return;const dx=e.clientX-startX,dy=e.clientY-startY;if(dx>12&&Math.abs(dx)>Math.abs(dy))bubble.style.transform=`translateX(${Math.min(dx,72)}px)`});const finish=e=>{if(!tracking)return;const dx=e.clientX-startX,dy=e.clientY-startY;tracking=false;bubble.style.transform='';if(dx>=55&&Math.abs(dx)>Math.abs(dy)*1.15){bubble.dataset.hnSwiped='1';selectMessage(bubble.dataset.messageId);}};bubble.addEventListener('pointerup',finish);bubble.addEventListener('pointercancel',()=>{tracking=false;bubble.style.transform='';});});
    listEl.querySelectorAll('.hn-chat-photo-button').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();openLightbox(btn.dataset.photoUrl);}));
    listEl.querySelectorAll('.hn-chat-audio-player').forEach(box=>{const audio=box.querySelector('audio'),play=box.querySelector('.hn-chat-audio-play'),bar=box.querySelector('.hn-chat-audio-progress'),duration=box.querySelector('.hn-chat-audio-duration');if(!audio||!play)return;const refresh=()=>{const dur=audio.duration||Number(audio.dataset.duration)||0;if(bar)bar.value=dur?(audio.currentTime/dur)*100:0;if(duration)duration.textContent=`${formatDuration(audio.currentTime)} / ${formatDuration(dur)}`;play.textContent=audio.paused?'▶':'❚❚';};play.addEventListener('click',e=>{e.stopPropagation();if(audio.paused)audio.play().catch(()=>{});else audio.pause();});audio.addEventListener('timeupdate',refresh);audio.addEventListener('loadedmetadata',refresh);audio.addEventListener('ended',refresh);bar?.addEventListener('input',e=>{e.stopPropagation();if(audio.duration)audio.currentTime=(Number(bar.value)/100)*audio.duration;});refresh();});
  }

  function pickAudioMime(){if(!window.MediaRecorder)return '';return ['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t))||'';}
  function updateRecordingUI(){const box=chatScreen?.querySelector('.hn-chat-recording'),time=chatScreen?.querySelector('.hn-chat-recording-time');if(!box||!time)return;box.classList.add('is-visible');time.textContent=formatDuration((Date.now()-recordingStartedAt)/1000);}
  function stopRecordingTimer(){if(recordingTimer)clearInterval(recordingTimer);recordingTimer=null;}
  function resetRecordingUI(pending=false){stopRecordingTimer();const box=chatScreen?.querySelector('.hn-chat-recording'),time=chatScreen?.querySelector('.hn-chat-recording-time');if(box)box.classList.toggle('is-visible',pending);if(box)box.classList.toggle('is-pending',pending);if(time&&!pending)time.textContent='00:00';micEl?.classList.remove('is-recording');micEl?.setAttribute('aria-label','Grabar nota de voz');micEl?.setAttribute('title','Grabar nota de voz');if(pending){const status=chatScreen?.querySelector('.hn-chat-recording-status');if(status)status.textContent='NOTA DE VOZ LISTA';if(time)time.textContent=formatDuration(pendingVoice?.duration||0);}}

  function startRecording(){
    if(pendingMedia.length){alert('Primero envía o elimina las fotos/videos seleccionados.');return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){alert('Este dispositivo o navegador no permite grabar notas de voz.');return;}const mimeType=pickAudioMime();navigator.mediaDevices.getUserMedia({audio:true}).then(stream=>{audioChunks=[];mediaRecorder=mimeType?new MediaRecorder(stream,{mimeType}):new MediaRecorder(stream);recordingStartedAt=Date.now();micEl?.classList.add('is-recording');micEl?.setAttribute('aria-label','Detener grabación');micEl?.setAttribute('title','Detener grabación');updateRecordingUI();recordingTimer=setInterval(updateRecordingUI,250);mediaRecorder.ondataavailable=e=>{if(e.data?.size)audioChunks.push(e.data)};mediaRecorder.onerror=()=>{stream.getTracks().forEach(t=>t.stop());mediaRecorder=null;resetRecordingUI(false);alert('No se pudo grabar el audio.');};mediaRecorder.onstop=()=>{stopRecordingTimer();stream.getTracks().forEach(t=>t.stop());const duration=Math.max(1,Math.round((Date.now()-recordingStartedAt)/1000));const blob=new Blob(audioChunks,{type:mediaRecorder?.mimeType||mimeType||'audio/webm'});mediaRecorder=null;if(!blob.size)return;pendingVoice={blob,duration};resetRecordingUI(true);updateSendState();inputEl?.focus();};mediaRecorder.start();}).catch(error=>{console.error('HAVANA NICE microphone permission failed:',error);alert('Necesitamos permiso para usar el micrófono.');});
  }
  function stopRecording(){if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();}
  function toggleRecording(){if(micEl?.disabled)return;if(mediaRecorder&&mediaRecorder.state==='recording')stopRecording();else startRecording();}

  function getVideoDuration(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),video=document.createElement('video');video.preload='metadata';video.onloadedmetadata=()=>{const d=Number(video.duration)||0;URL.revokeObjectURL(url);resolve(d);};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('No se pudo leer el video.'));};video.src=url;});}
  async function handleMediaFiles(fileList){const files=[...fileList];if(!files.length)return;if(pendingVoice){pendingVoice=null;resetRecordingUI(false);}if(pendingMedia.length+files.length>MAX_MEDIA){alert(`Puedes subir máximo ${MAX_MEDIA} fotos/videos por envío.`);mediaEl.value='';return;}for(const file of files){if(!file.type.startsWith('image/')&&!file.type.startsWith('video/')){alert('Solo puedes subir fotos o videos.');continue;}if(file.type.startsWith('video/')){try{const duration=await getVideoDuration(file);if(!duration||duration>MAX_VIDEO_SECONDS){alert(`El video "${file.name}" supera el máximo de 5 minutos.`);continue;}}catch(_){alert(`No se pudo revisar el video "${file.name}".`);continue;}}pendingMedia.push(file);}mediaEl.value='';renderPendingMedia();updateSendState();}
  function renderPendingMedia(){const box=chatScreen?.querySelector('.hn-chat-media-pending');if(!box)return;if(!pendingMedia.length){box.classList.remove('is-visible');box.innerHTML='';return;}box.classList.add('is-visible');box.innerHTML=pendingMedia.map((file,i)=>{const url=URL.createObjectURL(file),tag=file.type.startsWith('video/')?'video':'img';return `<div class="hn-chat-pending-item"><${tag} src="${url}" ${tag==='video'?'muted':''}></${tag}><button class="hn-chat-pending-remove" type="button" data-index="${i}" aria-label="Eliminar archivo">×</button></div>`;}).join('');box.querySelectorAll('.hn-chat-pending-remove').forEach(btn=>btn.addEventListener('click',()=>{pendingMedia.splice(Number(btn.dataset.index),1);renderPendingMedia();updateSendState();}));}

  async function uploadVoiceNote(blob,duration){const sb=client(),p=currentProfile();if(!sb||!p?.id||!blob?.size)throw new Error('No se pudo preparar el audio.');const mime=blob.type||'audio/webm',ext=mime.includes('mp4')?'m4a':mime.includes('ogg')?'ogg':'webm',path=`${p.id}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await sb.storage.from(AUDIO_BUCKET).upload(path,blob,{contentType:mime,upsert:false});if(uploadError)throw uploadError;const {data:urlData}=sb.storage.from(AUDIO_BUCKET).getPublicUrl(path);const audioUrl=urlData?.publicUrl;if(!audioUrl)throw new Error('No se pudo obtener la URL del audio.');const {data,error}=await sb.rpc('send_chat_audio',{p_profile_id:p.id,p_audio_url:audioUrl,p_audio_duration:duration});if(error)throw error;addLocalRow(data);}
  async function uploadMediaFiles(files){const sb=client(),p=currentProfile();if(!sb||!p?.id||!files.length)throw new Error('No se pudo preparar la multimedia.');const urls=[],types=[];for(const file of files){const isVideo=file.type.startsWith('video/'),ext=(file.name.split('.').pop()||(isVideo?'mp4':'jpg')).toLowerCase().replace(/[^a-z0-9]/g,'')||(isVideo?'mp4':'jpg');const path=`${p.id}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from(MEDIA_BUCKET).upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const {data}=sb.storage.from(MEDIA_BUCKET).getPublicUrl(path);if(!data?.publicUrl)throw new Error('No se pudo obtener la URL del archivo.');urls.push(data.publicUrl);types.push(isVideo?'video':'image');}const {data,error}=await sb.rpc('send_chat_media',{p_profile_id:p.id,p_media_urls:urls,p_media_types:types,p_message:(inputEl?.value||'').trim().slice(0,MAX_LENGTH)});if(error)throw error;addLocalRow(data);}
  function addLocalRow(data){const row=Array.isArray(data)?data[0]:data;if(row&&!messages.some(m=>m.id===row.id)){messages.push(row);messages.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));render();}markRead();}
  function updateSendState(){if(!sendEl)return;const text=(inputEl?.value||'').trim();if(mediaRecorder&&mediaRecorder.state==='recording'){sendEl.textContent='GRABANDO...';sendEl.disabled=true;}else if(pendingVoice){sendEl.textContent='ENVIAR NOTA DE VOZ';sendEl.disabled=false;}else if(pendingMedia.length){sendEl.textContent=`ENVIAR ${pendingMedia.length} ${pendingMedia.length===1?'ARCHIVO':'ARCHIVOS'}`;sendEl.disabled=false;}else{sendEl.textContent='ENVIAR';sendEl.disabled=!text||text.length>MAX_LENGTH;}}

  function buildScreen(){
    if(chatScreen)return chatScreen;ensureStyles();chatScreen=document.createElement('section');chatScreen.className='screen hn-chat-screen';chatScreen.id='hn-chat-screen';chatScreen.innerHTML=`<div class="hn-chat-wrap"><div class="hn-chat-head"><h1 class="hn-chat-head-title metallic-gold">CHAT DE INFORMACIÓN</h1><div class="hn-chat-head-sub">COMUNICACIÓN INTERNA · TIEMPO REAL</div></div><div class="hn-chat-list" aria-live="polite"></div><div class="hn-chat-reply"><div class="hn-chat-reply-line"></div><div class="hn-chat-reply-copy"><div class="hn-chat-reply-label">RESPONDER</div><div class="hn-chat-reply-text"></div></div><button class="hn-chat-reply-close" type="button" aria-label="Cerrar respuesta">×</button></div><form class="hn-chat-compose"><input class="hn-chat-media-input" type="file" accept="image/*,video/*" multiple hidden><div class="hn-chat-media-pending"></div><div class="hn-chat-input-wrap"><textarea class="hn-chat-input" rows="3" maxlength="1000" placeholder="Escribe un mensaje..."></textarea><button class="hn-chat-attach" type="button" aria-label="Subir fotos o videos" title="Subir fotos o videos">＋</button><button class="hn-chat-mic" type="button" aria-label="Grabar nota de voz" title="Grabar nota de voz">🎙</button></div><div class="hn-chat-recording"><span class="hn-chat-recording-status">GRABANDO NOTA DE VOZ</span><span class="hn-chat-recording-time">00:00</span></div><button class="hn-chat-send" type="submit">ENVIAR</button></form></div>`;
    document.querySelector('.experience')?.appendChild(chatScreen);listEl=chatScreen.querySelector('.hn-chat-list');inputEl=chatScreen.querySelector('.hn-chat-input');sendEl=chatScreen.querySelector('.hn-chat-send');micEl=chatScreen.querySelector('.hn-chat-mic');mediaEl=chatScreen.querySelector('.hn-chat-media-input');const attachEl=chatScreen.querySelector('.hn-chat-attach');chatScreen.querySelector('.hn-chat-compose').addEventListener('submit',sendMessage);chatScreen.querySelector('.hn-chat-reply-close').addEventListener('click',closeReply);micEl.addEventListener('click',toggleRecording);attachEl.addEventListener('click',()=>{if(!mediaRecorder)mediaEl?.click();});mediaEl.addEventListener('change',()=>handleMediaFiles(mediaEl.files));inputEl.addEventListener('input',()=>{inputEl.style.height='auto';inputEl.style.height=Math.min(inputEl.scrollHeight,150)+'px';updateSendState();});inputEl.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();chatScreen.querySelector('.hn-chat-compose').requestSubmit();}});buildLightbox();return chatScreen;
  }

  function render(){
    if(!listEl)return;if(!messages.length){listEl.innerHTML='<div class="hn-chat-empty">Aún no hay mensajes</div>';return;}const me=currentProfile();let lastDay='';listEl.innerHTML=messages.map(m=>{const day=dayLabel(m.created_at),mine=!!me&&String(m.profile_id)===String(me.id),parsed=parseReplyMessage(m.message);let html='';if(day!==lastDay){html+=`<div class="hn-chat-day">${esc(day)}</div>`;lastDay=day;}html+=`<div class="hn-chat-row ${mine?'mine':'other'}"><div class="hn-chat-bubble" data-message-id="${esc(m.id)}"><div class="hn-chat-sender">${esc(m.sender_name||'MIEMBRO')}</div>`;if(parsed.quote)html+=`<div class="hn-chat-quoted"><div class="hn-chat-quoted-sender">${esc(parsed.quote.sender)}</div><div class="hn-chat-quoted-text">${esc(parsed.quote.text)}</div></div>`;
      if(m.message_type==='audio'&&m.audio_url){html+=`<div class="hn-chat-audio-label"><span class="hn-chat-audio-icon">🎙</span><span>NOTA DE VOZ</span></div><div class="hn-chat-audio-player"><button class="hn-chat-audio-play" type="button">▶</button><input class="hn-chat-audio-progress" type="range" min="0" max="100" value="0"><span class="hn-chat-audio-duration">00:00 / ${esc(formatDuration(m.audio_duration))}</span><audio class="hn-chat-audio-native" preload="metadata" data-duration="${esc(m.audio_duration||0)}" src="${esc(m.audio_url)}"></audio></div>`;
      }else if(m.message_type==='media'&&Array.isArray(m.media_urls)){if(parsed.text)html+=`<div class="hn-chat-text">${esc(parsed.text)}</div>`;html+=`<div class="hn-chat-media-grid">${m.media_urls.map((url,i)=>{const type=Array.isArray(m.media_types)?m.media_types[i]:'image';return `<div class="hn-chat-media-item">${type==='video'?`<video controls controlsList="nodownload noplaybackrate nofullscreen noremoteplayback" disablePictureInPicture preload="metadata" src="${esc(url)}"></video>`:`<button class="hn-chat-photo-button" type="button" data-photo-url="${esc(url)}" aria-label="Abrir foto"><img loading="lazy" src="${esc(url)}" alt="Foto compartida"></button>`}</div>`;}).join('')}</div>`;
      }else html+=`<div class="hn-chat-text">${esc(parsed.text)}</div>`;html+=`<div class="hn-chat-time">${esc(formatTime(m.created_at))}</div></div></div>`;return html;}).join('');wireMessageInteractions();if(replyTarget){const current=messages.find(m=>m.id===replyTarget.id);if(current)selectMessage(current.id);else closeReply();}requestAnimationFrame(()=>{listEl.scrollTop=listEl.scrollHeight;});
  }

  function updateUnread(){const module=ensureHomeModule();if(!module)return;const last=localStorage.getItem(readKey()),lastTime=last?Date.parse(last):NaN,count=Number.isNaN(lastTime)?messages.length:messages.filter(m=>Date.parse(m.created_at)>lastTime).length;let badge=module.querySelector('.hn-chat-unread');if(count<=0){if(badge)badge.remove();return;}if(!badge){badge=document.createElement('span');badge.className='hn-chat-unread';badge.style.cssText='position:absolute;top:10px;right:48px;min-width:19px;height:19px;padding:0 5px;border-radius:12px;display:flex;align-items:center;justify-content:center;background:#e5bd62;color:#020302;font-size:9px;font-weight:700;';module.appendChild(badge);}badge.textContent=count>99?'99+':String(count);badge.hidden=false;}
  function markRead(){localStorage.setItem(readKey(),new Date().toISOString());updateUnread();}
  async function loadMessages(){const sb=client();if(!sb)return;const {data,error}=await sb.from(CHAT_TABLE).select('id,profile_id,sender_name,message,created_at,message_type,audio_url,audio_duration,media_urls,media_types').order('created_at',{ascending:true}).limit(200);if(error){console.warn('HAVANA NICE chat load failed:',error);return;}messages=data||[];render();updateUnread();}

  async function sendMessage(e){e.preventDefault();if(mediaRecorder&&mediaRecorder.state==='recording')return;const sb=client(),p=currentProfile();if(!sb||!p?.id)return;sendEl.disabled=true;try{if(pendingVoice){const voice=pendingVoice;pendingVoice=null;await uploadVoiceNote(voice.blob,voice.duration);inputEl.value='';inputEl.style.height='auto';closeReply();resetRecordingUI(false);return;}if(pendingMedia.length){const files=[...pendingMedia];pendingMedia=[];renderPendingMedia();const previewUrls=files.map(file=>URL.createObjectURL(file));const tempId=`local-media-${Date.now()}-${Math.random().toString(36).slice(2)}`;const tempRow={id:tempId,profile_id:p.id,sender_name:p.sender_name||p.name||p.full_name||'TÚ',message:(inputEl?.value||'').trim().slice(0,MAX_LENGTH),created_at:new Date().toISOString(),message_type:'media',media_urls:previewUrls,media_types:files.map(file=>file.type.startsWith('video/')?'video':'image')};messages.push(tempRow);messages.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));render();try{await uploadMediaFiles(files);messages=messages.filter(m=>m.id!==tempId);previewUrls.forEach(url=>URL.revokeObjectURL(url));render();}catch(error){messages=messages.filter(m=>m.id!==tempId);previewUrls.forEach(url=>URL.revokeObjectURL(url));pendingMedia=[...files,...pendingMedia];renderPendingMedia();throw error;}inputEl.value='';inputEl.style.height='auto';closeReply();return;}const text=(inputEl?.value||'').trim();if(!text||text.length>MAX_LENGTH){updateSendState();return;}let finalText=text;if(replyTarget){const sender=replyTarget.sender_name||'MIEMBRO';const quoted=replyTarget.message||(replyTarget.message_type==='audio'?'🎙 NOTA DE VOZ':replyTarget.message_type==='media'?'📎 FOTOS / VIDEOS':'');finalText=`↳ ${sender}: ${quoted}${REPLY_SEPARATOR}${text}`.slice(0,MAX_LENGTH);}const {data,error}=await sb.rpc('send_chat_message',{p_profile_id:p.id,p_message:finalText});if(error)throw error;inputEl.value='';inputEl.style.height='auto';closeReply();addLocalRow(data);}catch(error){console.error('HAVANA NICE chat send failed:',error);alert(error?.message||'No se pudo enviar.');}finally{updateSendState();inputEl?.focus();}}

  function subscribe(){const sb=client();if(!sb||chatChannel)return;chatChannel=sb.channel('hn-chat-realtime').on('postgres_changes',{event:'INSERT',schema:'public',table:CHAT_TABLE},payload=>{const row=payload.new;if(!messages.some(m=>m.id===row.id))messages.push(row);messages.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));render();if(chatScreen?.classList.contains('is-active'))markRead();else updateUnread();}).subscribe();}
  function closeChat(fromButton=false){if(!chatScreen)return;if(lightboxEl?.classList.contains('is-open'))closeLightbox();if(mediaRecorder&&mediaRecorder.state==='recording'){try{mediaRecorder.stop();}catch(_){}}closeReply();chatScreen.classList.remove('is-active');if(previousScreen)previousScreen.classList.add('is-active');else document.getElementById('homeScreen')?.classList.add('is-active');const video=document.getElementById('backgroundVideo');if(video)video.muted=videoWasMuted;if(historyArmed&&fromButton){historyArmed=false;try{history.back();}catch(_){}}else if(!fromButton)historyArmed=false;}
  function openChat(fromPopState=false){buildScreen();previousScreen=document.querySelector('.screen.is-active:not(#hn-chat-screen)')||document.getElementById('homeScreen');document.querySelectorAll('.screen').forEach(s=>{if(s!==chatScreen)s.classList.remove('is-active')});chatScreen.classList.add('is-active');markRead();render();const video=document.getElementById('backgroundVideo');if(video){videoWasMuted=!!video.muted;video.muted=true;video.play().catch(()=>{});}if(!fromPopState&&!historyArmed){try{history.pushState({...history.state,hnChat:true},'',location.href);historyArmed=true;}catch(_){}}setTimeout(()=>inputEl?.focus(),250);}
  function wireModule(){const module=ensureHomeModule();if(!module||module.dataset.hnChatBound==='1')return;module.dataset.hnChatBound='1';module.addEventListener('click',()=>openChat());}
  function wireNativeBack(){window.addEventListener('popstate',()=>{if(lightboxHistory||lightboxEl?.classList.contains('is-open')){closeLightbox(true);return;}if(chatScreen?.classList.contains('is-active'))closeChat(false);});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&lightboxEl?.classList.contains('is-open'))closeLightbox();});}
  async function init(){if(initialized)return;initialized=true;wireModule();buildScreen();wireNativeBack();await loadMessages();subscribe();setInterval(async()=>{if(!chatScreen?.classList.contains('is-active'))await loadMessages();},5000);}
  const boot=()=>setTimeout(init,250);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();