/* HAVANA NICE — FAMILIA HAVANA NICE / SINGLE OWNER / iOS SAFE */
(()=>{'use strict';
const FAMILY=[
  ['FER & NOA','HAVANA NICE','fer-noa'],
  ['ORLYS SHOW','MÚSICO','orly-show'],
  ['JALI','MÚSICO','jali'],
  ['RAFA','MÚSICO','rafa'],
  ['ANDY REY','MÚSICO','andy-rey']
];
const SUPABASE_URL='https://xzfradccsxonmauinecl.supabase.co';
const SUPABASE_KEY='sb_publishable_Ip5rGK0UVXIfOjs_RQ_LhA_c14foHN9';
const MEDIA_FUNCTION=SUPABASE_URL+'/functions/v1/family-profile-media-v1';
const DEVICE_MODULE='./musician-device-access-v1.js?v=415d2212baeec5cd7d2a46cfc79b50f45a0256cf';
const PROFILE_SELECT='id,member_key,name,role,bio,avatar_path,cover_path,active,sort_order,updated_at';
const IS_IOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
let supabaseClient=null;
let familyScreen=null;
let profileScreen=null;
let editorScreen=null;
let editorHistory=false;
let familyHistory=false;
let profileHistory=false;
let currentProfile=null;
let activeProfileKey=null;
let profileRequest=0;
let editorRequest=0;
let pending={avatar:null,cover:null};
let previewUrls={avatar:null,cover:null};
let realtimeChannel=null;
let deviceModule=null;
let familyLoadPromise=null;
let ownLoadPromise=null;
const profileCache=new Map();
const $=s=>document.querySelector(s);
const experience=()=>$('.experience');
const home=()=>$('#homeScreen');
function username(){try{return String(JSON.parse(sessionStorage.getItem('hn_profile')||'{}').username||'').trim().toLowerCase()}catch(_){return ''}}
function memberKey(){return ({fer:'fer-noa',orly:'orly-show',jali:'jali',rafa:'rafa',andy:'andy-rey'})[username()]||null}
function personFor(key){return FAMILY.find(x=>x[2]===key)||null}
async function getDeviceApi(){if(deviceModule)return deviceModule;deviceModule=await import(DEVICE_MODULE);return deviceModule}
async function deviceToken(){try{return (await getDeviceApi()).getDeviceToken()}catch(_){try{return localStorage.getItem('hn_musician_device_token_v1')||''}catch(__){return ''}}}
async function db(){if(window.hnSupabase)return window.hnSupabase;if(supabaseClient)return supabaseClient;const m=await import('https://esm.sh/@supabase/supabase-js@2');supabaseClient=m.createClient(SUPABASE_URL,SUPABASE_KEY);return supabaseClient}
async function getProfileFromFunction(key){const r=await fetch(MEDIA_FUNCTION+'?member_key='+encodeURIComponent(key)+'&v='+Date.now(),{method:'GET',cache:'no-store',headers:{Accept:'application/json','Cache-Control':'no-cache'}});let data={};try{data=await r.json()}catch(_){}if(!r.ok||!data.ok)throw Error(data.error||'No fue posible cargar el perfil');return data.profile||null}
async function getProfile(key){if(!key)return null;try{const c=await db();const {data,error}=await c.from('family_profiles').select(PROFILE_SELECT).eq('member_key',key).eq('active',true).maybeSingle();if(!error)return data||null;console.warn('[HN family] direct profile read failed',error)}catch(e){console.warn('[HN family] direct profile read failed',e)}return getProfileFromFunction(key)}
async function getAllProfiles(){try{const c=await db();const {data,error}=await c.from('family_profiles').select(PROFILE_SELECT).eq('active',true).order('sort_order',{ascending:true});if(!error&&Array.isArray(data))return data;console.warn('[HN family] direct family read failed',error)}catch(e){console.warn('[HN family] direct family read failed',e)}const rows=await Promise.all(FAMILY.map(async p=>{try{return await getProfileFromFunction(p[2])}catch(_){return null}}));return rows.filter(Boolean)}
function mediaUrl(path,updated,key=''){if(!path)return '';const clean=path.split('/').map(encodeURIComponent).join('/');const version=updated||path;return SUPABASE_URL+'/storage/v1/object/public/family-media/'+clean+'?v='+encodeURIComponent(version)+'&member='+encodeURIComponent(key||path)}
async function validateDevice(){const api=await getDeviceApi(),u=username();if(!u)throw Error('Sesión de músico no disponible');const r=await api.validateSession(u);const a=Array.isArray(r?.data)?r.data[0]:r?.data;if(r?.error)throw r.error;if(a?.status==='authorized')return a;if(a?.status==='blocked')throw Error('Este dispositivo está bloqueado');if(a?.status==='pending')throw Error('Este dispositivo está pendiente de autorización');throw Error('Dispositivo no autorizado')}
function injectCss(){if($('#hn-family-profile-css'))return;const s=document.createElement('style');s.id='hn-family-profile-css';s.textContent=`
.hn-family-media-img{display:block;width:100%;height:100%;margin:0;border:0;object-fit:cover;object-position:center;background:transparent;pointer-events:none;user-select:none;-webkit-user-select:none}
.hn-home-profile-wrap{display:flex;flex-direction:column;align-items:center;min-width:72px}.hn-home-profile-button{width:62px;height:62px;border:2px solid var(--gold);border-radius:50%;background:rgba(3,7,5,.9);box-shadow:0 0 0 4px rgba(0,0,0,.55),0 8px 22px rgba(0,0,0,.35);position:relative}.hn-home-profile-button>.hn-family-media-img{position:absolute;inset:0;border-radius:50%}.hn-home-profile-button:after{content:'✎';position:absolute;z-index:4;right:-5px;bottom:-2px;width:24px;height:24px;display:grid;place-items:center;border:1px solid var(--gold);border-radius:50%;background:#050806;color:var(--gold-light);font-size:11px}.hn-home-profile-label{margin-top:6px;color:rgba(244,241,232,.48);font-size:7px;letter-spacing:.16em;text-transform:uppercase}
#hnProfileEditor.hn-profile-editor{overflow:auto!important;-webkit-overflow-scrolling:touch}.hn-profile-editor-inner{position:relative;width:min(100%,650px);margin:auto}.hn-editor-cover{position:relative;height:190px;border:1px solid rgba(229,189,98,.42);border-radius:12px 12px 0 0;background:linear-gradient(135deg,#102219,#18271d,#050806);overflow:hidden}.hn-editor-cover>.hn-family-media-img{position:absolute;inset:0;z-index:0;border-radius:inherit}.hn-editor-cover:after{content:'';position:absolute;z-index:1;inset:0;background:linear-gradient(180deg,transparent,rgba(0,0,0,.62));pointer-events:none}.hn-editor-avatar{position:absolute;z-index:3;left:24px;top:134px;width:112px;height:112px;border:2px solid var(--gold);border-radius:50%;background:rgba(5,10,7,.9);box-shadow:0 0 0 5px rgba(2,3,2,.65)}.hn-editor-avatar>.hn-family-media-img{position:absolute;inset:0;border-radius:50%}.hn-editor-pencil{position:absolute;z-index:5;width:31px;height:31px;border:1px solid var(--gold);border-radius:50%;background:#050806;color:var(--gold-light);font-size:14px;line-height:1}.hn-editor-cover-pencil{right:12px;bottom:12px}.hn-editor-avatar-pencil{right:-4px;bottom:4px}.hn-editor-content{padding:72px 16px 28px}.hn-editor-name{margin:0;color:var(--white);font:400 29px Georgia,serif;letter-spacing:.04em;text-transform:uppercase}.hn-editor-role{margin:9px 0 18px;color:rgba(244,241,232,.46);font-size:8px;letter-spacing:.22em;text-transform:uppercase}.hn-editor-status{min-height:18px;color:rgba(244,241,232,.58);font-size:9px;letter-spacing:.1em;text-transform:uppercase}.hn-editor-status.error{color:#e9a0a0}.hn-editor-status.success{color:var(--gold-light)}.hn-editor-save{width:100%;height:48px;margin-top:14px;border:1px solid var(--gold);background:linear-gradient(105deg,rgba(116,77,20,.28),rgba(255,221,130,.12),rgba(116,77,20,.28));color:var(--gold-light);font-size:10px;font-weight:600;letter-spacing:.24em;text-transform:uppercase}.hn-editor-save:disabled{opacity:.42;cursor:not-allowed}.hn-editor-file{display:none!important}.hn-editor-back{width:100%;margin-top:10px}
#hnFamilyScreen.family-screen{overflow:auto!important;-webkit-overflow-scrolling:touch;padding-bottom:max(92px,env(safe-area-inset-bottom))}.family-inner{width:min(100%,650px);margin:auto}.family-header{margin-bottom:28px;text-align:center}.family-caption{margin:17px 0 0;color:rgba(244,241,232,.70);font-size:12px;letter-spacing:.30em;text-transform:uppercase}.family-list{display:flex;flex-direction:column;gap:10px;width:100%}.family-member{appearance:none;-webkit-appearance:none;position:relative;width:100%;min-height:70px;display:flex;align-items:center;gap:16px;padding:15px 18px;border:1px solid rgba(229,189,98,.58);border-radius:12px;background:linear-gradient(105deg,rgba(0,0,0,.62),rgba(20,14,5,.28),rgba(0,0,0,.50));color:var(--white);font:inherit;text-align:left;box-shadow:inset 0 0 0 1px rgba(255,255,255,.025),0 8px 24px rgba(0,0,0,.16);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);cursor:pointer;overflow:hidden}.family-member:active{transform:scale(.985)}.family-member:hover{border-color:var(--gold-light)}.family-number{width:30px;flex:0 0 30px;color:var(--gold);font:400 14px Georgia,serif;letter-spacing:.08em}.family-member-avatar{width:44px;height:44px;flex:0 0 44px;border:1px solid rgba(229,189,98,.72);border-radius:50%;background:linear-gradient(135deg,#102219,#18271d,#050806);box-shadow:0 0 0 3px rgba(0,0,0,.32);overflow:hidden}.family-member-avatar>.hn-family-media-img{border-radius:50%}.family-copy{min-width:0;flex:1;display:flex;flex-direction:column;gap:6px}.family-name{display:block;color:var(--white);font-size:12px;font-weight:500;letter-spacing:.22em;line-height:1.25;text-transform:uppercase}.family-role{display:block;color:rgba(244,241,232,.46);font-size:8px;letter-spacing:.18em;line-height:1.2;text-transform:uppercase}.family-arrow{flex:0 0 auto;color:var(--gold-light);font-size:25px;font-weight:300;line-height:1}.family-footer{margin-top:18px}.family-footer .back-button{width:100%}
#hnFamilyProfileScreen.family-profile-screen{overflow:auto!important;-webkit-overflow-scrolling:touch;padding-bottom:max(92px,env(safe-area-inset-bottom))}.family-profile-inner{width:min(100%,650px);margin:auto}.family-profile-cover{position:relative;height:220px;border:1px solid rgba(229,189,98,.42);border-radius:12px 12px 0 0;background:linear-gradient(135deg,#102219,#18271d,#050806);overflow:visible}.family-profile-cover>.hn-family-media-img{position:absolute;inset:0;z-index:0;border-radius:11px 11px 0 0}.family-profile-cover:after{content:'';position:absolute;z-index:1;inset:0;background:linear-gradient(180deg,transparent 45%,rgba(0,0,0,.72) 100%);pointer-events:none;border-radius:inherit}.family-profile-avatar{position:absolute;z-index:2;left:24px;bottom:-58px;width:116px;height:116px;border:2px solid var(--gold);border-radius:50%;background:rgba(5,10,7,.92);box-shadow:0 0 0 5px rgba(2,3,2,.72),0 12px 30px rgba(0,0,0,.35);overflow:hidden}.family-profile-avatar>.hn-family-media-img{border-radius:50%}.family-profile-content{padding:74px 16px 28px}.family-profile-name{margin:0;color:var(--white);font:400 30px Georgia,serif;letter-spacing:.04em;text-transform:uppercase}.family-profile-role{margin:9px 0 24px;color:rgba(244,241,232,.46);font-size:8px;letter-spacing:.22em;text-transform:uppercase}.family-profile-bio-box{padding:18px;border:1px solid rgba(229,189,98,.28);border-radius:12px;background:rgba(0,0,0,.28)}.family-profile-bio-title{margin:0 0 10px;color:var(--gold);font-size:9px;font-weight:500;letter-spacing:.24em;text-transform:uppercase}.family-profile-bio{color:rgba(244,241,232,.76);font-size:12px;line-height:1.7;letter-spacing:.04em;white-space:pre-line}.family-profile-bio.is-placeholder{color:rgba(244,241,232,.35);font-style:italic}.family-profile-back{width:100%;margin-top:16px}
.hn-family-ios #hnFamilyScreen,.hn-family-ios #hnFamilyProfileScreen,.hn-family-ios #hnProfileEditor{transform:none!important;will-change:auto!important}.hn-family-ios .family-member{backdrop-filter:none!important;-webkit-backdrop-filter:none!important;background:linear-gradient(105deg,rgba(0,0,0,.76),rgba(20,14,5,.40),rgba(0,0,0,.68))}
@media(max-width:520px){.hn-home-profile-button{width:57px;height:57px}.hn-editor-cover{height:155px}.hn-editor-avatar{left:18px;top:107px;width:96px;height:96px}.hn-editor-content{padding-top:62px}.hn-editor-name{font-size:25px}.family-member{min-height:64px;padding:13px 15px;gap:11px}.family-member-avatar{width:42px;height:42px;flex-basis:42px}.family-number{width:22px;flex-basis:22px}.family-name{font-size:10px;letter-spacing:.18em}.family-profile-cover{height:175px}.family-profile-avatar{left:18px;bottom:-48px;width:96px;height:96px}.family-profile-content{padding-top:62px}.family-profile-name{font-size:25px}}
`;document.head.appendChild(s)}
function clearBoxImage(box){if(!box)return;Array.from(box.children).forEach(child=>{if(child.tagName==='IMG'&&child.classList.contains('hn-family-media-img'))child.remove()})}
function setBoxImage(box,url){if(!box)return null;clearBoxImage(box);if(!url)return null;const img=document.createElement('img');img.className='hn-family-media-img';img.alt='';img.decoding='async';img.loading='eager';img.draggable=false;img.addEventListener('error',()=>{if(img.isConnected)img.remove()},{once:true});img.src=url;box.prepend(img);return img}
function renderMedia(root,row){const c=root?.querySelector('[data-cover]'),a=root?.querySelector('[data-avatar]');setBoxImage(c,row?.cover_path?mediaUrl(row.cover_path,row.updated_at,row.member_key):'');setBoxImage(a,row?.avatar_path?mediaUrl(row.avatar_path,row.updated_at,row.member_key):'')}
function cacheProfile(row){if(row?.member_key)profileCache.set(row.member_key,row);return row}
function status(text,error=false){const x=editorScreen?.querySelector('.hn-editor-status');if(x){x.textContent=text||'';x.className='hn-editor-status'+(error?' error':text?' success':'')}}
async function decodeLocalImage(file){if('createImageBitmap'in window){try{const bitmap=await createImageBitmap(file);return{source:bitmap,width:bitmap.width,height:bitmap.height,cleanup:()=>bitmap.close?.()}}catch(_){}}const url=URL.createObjectURL(file);const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('No fue posible leer la imagen'));img.src=url});return{source:img,width:img.naturalWidth,height:img.naturalHeight,cleanup:()=>URL.revokeObjectURL(url)}}
async function compressImage(file,max){const decoded=await decodeLocalImage(file);try{const scale=Math.min(1,max/Math.max(decoded.width,decoded.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(decoded.width*scale));canvas.height=Math.max(1,Math.round(decoded.height*scale));const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw Error('No fue posible preparar la imagen');ctx.drawImage(decoded.source,0,0,canvas.width,canvas.height);let blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.84));if(!blob)blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.88));if(!blob)throw Error('No fue posible preparar la imagen');const ext=blob.type==='image/webp'?'webp':'jpg';return new File([blob],Date.now()+'.'+ext,{type:blob.type})}finally{decoded.cleanup()}}
function setPending(type,file){if(previewUrls[type])URL.revokeObjectURL(previewUrls[type]);previewUrls[type]=URL.createObjectURL(file);pending[type]=file;const target=editorScreen?.querySelector(type==='avatar'?'[data-avatar]':'[data-cover]');setBoxImage(target,previewUrls[type]);const save=editorScreen?.querySelector('.hn-editor-save');if(save)save.disabled=!pending.avatar&&!pending.cover;status('Cambios listos para guardar.')}
async function selectImage(type,file){try{status('Preparando imagen…');const prepared=await compressImage(file,type==='avatar'?700:1800);setPending(type,prepared)}catch(e){console.error('[HN family profile]',e);status(e.message||'No fue posible preparar la imagen.',true)}}
async function uploadPending(type,file){const own=memberKey(),person=personFor(own);if(!person)throw Error('Perfil de músico no disponible');const fd=new FormData();fd.append('username',username());fd.append('device_token',await deviceToken());fd.append('member_key',person[2]);fd.append('media_type',type);fd.append('file',file,file.name);const r=await fetch(MEDIA_FUNCTION,{method:'POST',body:fd,cache:'no-store'});let data={};try{data=await r.json()}catch(_){}if(!r.ok||!data.ok)throw Error(data.error||'No fue posible guardar la imagen');return data.profile}
function clearPending(){pending={avatar:null,cover:null};Object.keys(previewUrls).forEach(k=>{if(previewUrls[k]){URL.revokeObjectURL(previewUrls[k]);previewUrls[k]=null}})}
function setBio(row){const el=profileScreen?.querySelector('.family-profile-bio');if(!el)return;const text=String(row?.bio||'').trim();el.textContent=text||'Biografía próximamente.';el.classList.toggle('is-placeholder',!text)}
function renderProfile(row,key=activeProfileKey){if(!profileScreen)return;const person=personFor(key);profileScreen.querySelector('.family-profile-name').textContent=row?.name||person?.[0]||'';profileScreen.querySelector('.family-profile-role').textContent=row?.role||person?.[1]||'';setBio(row);renderMedia(profileScreen,row||null)}
function refreshHomeAvatar(row=currentProfile){const button=$('.hn-home-profile-button');if(!button)return;setBoxImage(button,row?.avatar_path?mediaUrl(row.avatar_path,row.updated_at,row.member_key):'')}
function applyFamilyRow(row,key=row?.member_key){const list=familyScreen?.querySelector('.family-list');if(!list||!key)return;const box=list.querySelector(`[data-member-key="${key}"] [data-list-avatar]`);setBoxImage(box,row?.avatar_path?mediaUrl(row.avatar_path,row.updated_at,key):'')}
function applyProfileUpdate(row){if(!row?.member_key)return;cacheProfile(row);if(row.member_key===memberKey()){currentProfile=row;refreshHomeAvatar(row);if(editorScreen?.classList.contains('is-active')&&!pending.avatar&&!pending.cover)renderMedia(editorScreen,row)}if(familyScreen)applyFamilyRow(row);if(profileScreen?.classList.contains('is-active')&&activeProfileKey===row.member_key)renderProfile(row,row.member_key)}
async function saveChanges(){if(!pending.avatar&&!pending.cover){status('No hay cambios por guardar.');return}const save=editorScreen?.querySelector('.hn-editor-save');if(save)save.disabled=true;try{status('Validando dispositivo…');await validateDevice();status('Guardando cambios…');let latest=currentProfile;if(pending.avatar){latest=await uploadPending('avatar',pending.avatar);pending.avatar=null;cacheProfile(latest)}if(pending.cover){latest=await uploadPending('cover',pending.cover);pending.cover=null;cacheProfile(latest)}if(latest){currentProfile=latest;renderMedia(editorScreen,latest);refreshHomeAvatar(latest);applyFamilyRow(latest);if(activeProfileKey===latest.member_key)renderProfile(latest,latest.member_key)}Object.keys(previewUrls).forEach(k=>{if(previewUrls[k]){URL.revokeObjectURL(previewUrls[k]);previewUrls[k]=null}});status('Cambios guardados.');setTimeout(()=>status(''),2200)}catch(e){console.error('[HN family profile]',e);status(e.message||'No fue posible guardar los cambios.',true)}finally{if(save)save.disabled=!pending.avatar&&!pending.cover}}
function buildEditor(){if(editorScreen)return;injectCss();editorScreen=document.createElement('section');editorScreen.id='hnProfileEditor';editorScreen.className='screen hn-profile-editor';editorScreen.innerHTML=`<div class="hn-profile-editor-inner"><div class="hn-editor-cover" data-cover><button class="hn-editor-pencil hn-editor-cover-pencil" data-type="cover" type="button" aria-label="Cambiar foto de portada">✎</button><input class="hn-editor-file" data-file="cover" type="file" accept="image/*"></div><div class="hn-editor-avatar" data-avatar><button class="hn-editor-pencil hn-editor-avatar-pencil" data-type="avatar" type="button" aria-label="Cambiar foto de perfil">✎</button><input class="hn-editor-file" data-file="avatar" type="file" accept="image/*"></div><div class="hn-editor-content"><h1 class="hn-editor-name"></h1><p class="hn-editor-role"></p><div class="hn-editor-status" aria-live="polite"></div><button class="hn-editor-save" type="button" disabled>GUARDAR CAMBIOS</button><button class="back-button hn-editor-back" type="button">VOLVER</button></div></div>`;experience()?.append(editorScreen);editorScreen.querySelectorAll('.hn-editor-pencil').forEach(button=>button.addEventListener('click',()=>editorScreen.querySelector(`[data-file="${button.dataset.type}"]`)?.click()));editorScreen.querySelectorAll('.hn-editor-file').forEach(input=>input.addEventListener('change',()=>{const file=input.files?.[0];input.value='';if(file)selectImage(input.dataset.file,file)}));editorScreen.querySelector('.hn-editor-save').addEventListener('click',saveChanges);editorScreen.querySelector('.hn-editor-back').addEventListener('click',()=>closeEditor(true))}
function activateScreen(screen){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('is-active'));screen?.classList.add('is-active')}
async function openEditor(push=true){const own=memberKey();if(!own)return;buildEditor();const request=++editorRequest;clearPending();status('');const person=personFor(own);editorScreen.querySelector('.hn-editor-name').textContent=person?.[0]||'';editorScreen.querySelector('.hn-editor-role').textContent=person?.[1]||'';const cached=profileCache.get(own)||null;renderMedia(editorScreen,cached);activateScreen(editorScreen);if(push&&!editorHistory){history.pushState({hnFamilyEditor:true},'',location.href);editorHistory=true}try{const row=await getProfile(own);if(request!==editorRequest||!editorScreen?.classList.contains('is-active'))return;if(row){currentProfile=cacheProfile(row);renderMedia(editorScreen,row);refreshHomeAvatar(row)}}catch(e){console.warn('[HN family] editor profile load failed',e)}}
function closeEditor(back=false){++editorRequest;clearPending();editorScreen?.classList.remove('is-active');home()?.classList.add('is-active');if(back&&editorHistory){editorHistory=false;history.back()}else editorHistory=false}
async function refreshOwnProfile(){const own=memberKey();if(!own){currentProfile=null;refreshHomeAvatar(null);return null}if(ownLoadPromise)return ownLoadPromise;ownLoadPromise=(async()=>{try{const row=await getProfile(own);if(row){currentProfile=cacheProfile(row);refreshHomeAvatar(row)}else{currentProfile=null;refreshHomeAvatar(null)}return row}catch(e){console.warn('[HN family] home profile load failed',e);return null}finally{ownLoadPromise=null}})();return ownLoadPromise}
async function installHomeProfile(){const h=home(),top=h?.querySelector('.home-top');if(!h||!top)return;injectCss();let wrap=$('.hn-home-profile-wrap');if(!wrap){const old=[...top.querySelectorAll('button')].find(b=>/CERRAR\s+SESI[ÓO]N/i.test(b.textContent||''));wrap=document.createElement('div');wrap.className='hn-home-profile-wrap';wrap.innerHTML='<button class="hn-home-profile-button" type="button" aria-label="Editar mi perfil"></button><span class="hn-home-profile-label">Mi perfil</span>';if(old)old.replaceWith(wrap);else top.append(wrap);wrap.querySelector('button').addEventListener('click',()=>openEditor(true))}await refreshOwnProfile()}
function observeHomeActivation(){const h=home();if(!h||h.dataset.hnFamilyHomeObserver==='1')return;h.dataset.hnFamilyHomeObserver='1';new MutationObserver(()=>{if(h.classList.contains('is-active'))refreshOwnProfile()}).observe(h,{attributes:true,attributeFilter:['class']})}
async function loadFamilyProfiles(){if(familyLoadPromise)return familyLoadPromise;familyLoadPromise=(async()=>{try{const rows=await getAllProfiles();const byKey=new Map(rows.map(r=>[r.member_key,cacheProfile(r)]));FAMILY.forEach(p=>applyFamilyRow(byKey.get(p[2])||null,p[2]));return rows}catch(e){console.warn('[HN family] family list load failed',e);return[]}finally{familyLoadPromise=null}})();return familyLoadPromise}
function buildFamilyScreen(){if(familyScreen)return;injectCss();familyScreen=document.createElement('section');familyScreen.id='hnFamilyScreen';familyScreen.className='screen family-screen';familyScreen.innerHTML='<div class="family-inner"><div class="family-header"><h1 class="brand metallic-gold">FAMILIA HAVANA NICE</h1><div class="brand-line"></div><p class="family-caption">Nuestra familia</p></div><div class="family-list"></div><div class="family-footer"><button class="back-button" type="button">VOLVER</button></div></div>';experience()?.append(familyScreen);familyScreen.querySelector('.back-button').addEventListener('click',()=>closeFamily(true));renderFamilyList()}
function renderFamilyList(){const list=familyScreen?.querySelector('.family-list');if(!list)return;list.innerHTML=FAMILY.map((p,i)=>`<button class="family-member" type="button" data-member-key="${p[2]}"><span class="family-number">${String(i+1).padStart(2,'0')}</span><span class="family-member-avatar" data-list-avatar aria-hidden="true"></span><span class="family-copy"><span class="family-name">${p[0]}</span><span class="family-role">${p[1]}</span></span><span class="family-arrow">›</span></button>`).join('');list.querySelectorAll('[data-member-key]').forEach(b=>b.addEventListener('click',()=>openProfile(b.dataset.memberKey,true)))}
function closeFamily(back=false){familyScreen?.classList.remove('is-active');home()?.classList.add('is-active');if(back&&familyHistory){familyHistory=false;history.back()}else familyHistory=false}
function buildProfileScreen(){if(profileScreen)return;injectCss();profileScreen=document.createElement('section');profileScreen.id='hnFamilyProfileScreen';profileScreen.className='screen family-profile-screen';profileScreen.innerHTML='<div class="family-profile-inner"><div class="family-profile-cover" data-cover><div class="family-profile-avatar" data-avatar></div></div><div class="family-profile-content"><h1 class="family-profile-name"></h1><p class="family-profile-role"></p><div class="family-profile-bio-box"><h2 class="family-profile-bio-title">BIOGRAFÍA</h2><div class="family-profile-bio is-placeholder">Biografía próximamente.</div></div><button class="back-button family-profile-back" type="button">VOLVER</button></div></div>';experience()?.append(profileScreen);profileScreen.querySelector('.family-profile-back').addEventListener('click',()=>closeProfile(true))}
async function openProfile(key,push=true){if(!personFor(key))return;buildProfileScreen();activeProfileKey=key;const request=++profileRequest;renderProfile(profileCache.get(key)||null,key);activateScreen(profileScreen);if(push&&!profileHistory){history.pushState({hnFamilyProfile:key},'',location.href);profileHistory=true}try{const row=await getProfile(key);if(request!==profileRequest||activeProfileKey!==key||!profileScreen?.classList.contains('is-active'))return;if(row){cacheProfile(row);renderProfile(row,key);applyFamilyRow(row)}}catch(e){console.warn('[HN family] profile load failed',e)}}
function closeProfile(back=false){activeProfileKey=null;++profileRequest;renderMedia(profileScreen,null);profileScreen?.classList.remove('is-active');familyScreen?.classList.add('is-active');if(back&&profileHistory){profileHistory=false;history.back()}else profileHistory=false}
function openFamily(push=true){buildFamilyScreen();activeProfileKey=null;++profileRequest;activateScreen(familyScreen);FAMILY.forEach(p=>applyFamilyRow(profileCache.get(p[2])||null,p[2]));loadFamilyProfiles();if(push&&!familyHistory){history.pushState({hnFamily:true},'',location.href);familyHistory=true}}
function wireFamilyEntry(){if(document.documentElement.dataset.hnFamilyRouter==='1')return;document.documentElement.dataset.hnFamilyRouter='1';document.addEventListener('click',e=>{const target=e.target?.closest?.('[data-module="MÚSICOS"], [data-module="FAMILIA HAVANA NICE"], [data-family-entry]');if(!target)return;e.preventDefault();e.stopImmediatePropagation();openFamily(true)},true)}
function subscribeRealtime(){if(realtimeChannel)return;db().then(c=>{realtimeChannel=c.channel('family-profiles-ui-v3').on('postgres_changes',{event:'*',schema:'public',table:'family_profiles'},payload=>{const row=payload.new&&payload.new.member_key?payload.new:null;const old=payload.old&&payload.old.member_key?payload.old:null;if(row&&row.active!==false){applyProfileUpdate(row);return}const key=old?.member_key||row?.member_key;if(!key)return;profileCache.delete(key);if(key===memberKey()){currentProfile=null;refreshHomeAvatar(null)}applyFamilyRow(null,key);if(activeProfileKey===key)renderProfile(null,key)}).subscribe()}).catch(e=>console.warn('[HN family] realtime unavailable',e))}
function boot(){if(IS_IOS)document.documentElement.classList.add('hn-family-ios');injectCss();buildFamilyScreen();wireFamilyEntry();installHomeProfile();observeHomeActivation();subscribeRealtime();window.addEventListener('popstate',()=>{if(editorHistory){editorHistory=false;closeEditor(false)}else if(profileHistory){profileHistory=false;closeProfile(false)}else if(familyHistory){familyHistory=false;closeFamily(false)}});window.hnFamilyOpen=openFamily;window.hnFamilyProfileOpen=openProfile;window.hnFamilyEditorOpen=openEditor}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0),{once:true});else setTimeout(boot,0);
})();
