/* HAVANA NICE — FAMILIA HAVANA NICE / ORIGINAL EDITORIAL / PROFILE HOME */
(()=>{'use strict';
const F=[['FER & NOA','HAVANA NICE','fer-noa'],['ORLYS SHOW','MÚSICO','orlys-show'],['JALI','MÚSICO','jali'],['RAFA','MÚSICO','rafa'],['ANDY REY','MÚSICO','andy-rey']];
const U='https://xzfradccsxonmauinecl.supabase.co',K='sb_publishable_Ip5rGK0UVXIfOjs_RQ_LhA_c14foHN9',M=U+'/functions/v1/family-profile-media-v1',TK='hn_musician_device_token_v1';
let sb,fam,prof,edit,prev,hf=false,hp=false,he=false,ch;
const $=s=>document.querySelector(s),home=()=>$('#homeScreen'),usr=()=>{try{return String(JSON.parse(sessionStorage.getItem('hn_profile')||'{}').username||'').trim().toLowerCase()}catch(_){return ''}},key=()=>({fer:'fer-noa',orly:'orlys-show',jali:'jali',rafa:'rafa',andy:'andy-rey'})[usr()]||null;
function tok(){try{let t=localStorage.getItem(TK);if(t&&t.length>=16)return t;t=crypto?.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();localStorage.setItem(TK,t);return t}catch(_){return ''}}
async function db(){if(sb)return sb;const m=await import('https://esm.sh/@supabase/supabase-js@2');return sb=m.createClient(U,K)}
async function row(k){const c=await db(),r=await c.from('family_profiles').select('id,member_key,name,role,bio,avatar_path,cover_path,active,sort_order,updated_at').eq('member_key',k).maybeSingle();if(r.error)throw r.error;return r.data}
function media(p){return p?U+'/storage/v1/object/public/family-media/'+p.split('/').map(encodeURIComponent).join('/') :''}
async function valid(){const c=await db(),u=usr(),t=tok();if(!u||!t)throw Error('Sesión de músico no disponible');let r=await c.rpc('validate_musician_device_session',{p_username:u,p_device_token:t}),a=Array.isArray(r.data)?r.data[0]:r.data;if(r.error)throw r.error;if(a?.status==='authorized')return a;if(a?.status==='blocked')throw Error('Este dispositivo está bloqueado');r=await c.rpc('request_musician_device_access',{p_username:u,p_device_token:t,p_device_label:'Dispositivo móvil'});if(r.error)throw r.error;a=Array.isArray(r.data)?r.data[0]:r.data;if(a?.status==='authorized')return a;if(a?.status==='pending')throw Error('Este dispositivo está pendiente de autorización');throw Error('Dispositivo no autorizado')}
function css(){if($('#hn-family-profile-css'))return;const s=document.createElement('style');s.id='hn-family-profile-css';s.textContent=`
.hn-home-profile-wrap{display:flex;flex-direction:column;align-items:center;min-width:72px}.hn-home-profile-button{width:62px;height:62px;border:2px solid var(--gold);border-radius:50%;background:rgba(3,7,5,.9) center/cover no-repeat;box-shadow:0 0 0 4px rgba(0,0,0,.55),0 8px 22px rgba(0,0,0,.35);position:relative}.hn-home-profile-button:after{content:'✎';position:absolute;right:-5px;bottom:-2px;width:24px;height:24px;display:grid;place-items:center;border:1px solid var(--gold);border-radius:50%;background:#050806;color:var(--gold-light);font-size:11px}.hn-home-profile-label{margin-top:6px;color:rgba(244,241,232,.48);font-size:7px;letter-spacing:.16em;text-transform:uppercase}.hn-home-logout-moved{width:auto!important;min-width:0!important;height:auto!important;margin:9px auto 0!important;padding:3px 2px!important;border:0!important;background:transparent!important;color:rgba(244,241,232,.30)!important;font-size:7px!important;letter-spacing:.18em!important;text-transform:uppercase!important;box-shadow:none!important}.hn-profile-editor{overflow:auto}.hn-profile-editor-inner{width:min(100%,650px);margin:auto}.hn-editor-cover{position:relative;height:190px;border:1px solid rgba(229,189,98,.42);border-radius:12px 12px 0 0;background:linear-gradient(135deg,#102219,#18271d,#050806) center/cover no-repeat}.hn-editor-cover:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent,rgba(0,0,0,.62));pointer-events:none}.hn-editor-avatar{position:absolute;z-index:3;left:24px;bottom:-56px;width:112px;height:112px;border:2px solid var(--gold);border-radius:50%;background:rgba(5,10,7,.9) center/cover no-repeat;box-shadow:0 0 0 5px rgba(2,3,2,.65)}.hn-editor-pencil{position:absolute;z-index:5;width:31px;height:31px;border:1px solid var(--gold);border-radius:50%;background:#050806;color:var(--gold-light);font-size:14px}.hn-editor-cover-pencil{right:12px;bottom:12px}.hn-editor-avatar-pencil{right:-4px;bottom:4px}.hn-editor-content{padding:72px 16px 28px}.hn-editor-name{margin:0;color:var(--white);font:400 29px Georgia,serif;letter-spacing:.04em;text-transform:uppercase}.hn-editor-role{margin:9px 0;color:rgba(244,241,232,.46);font-size:8px;letter-spacing:.22em;text-transform:uppercase}.hn-editor-status{min-height:18px;color:rgba(244,241,232,.55);font-size:9px;letter-spacing:.1em;text-transform:uppercase}.hn-editor-status.error{color:#e9a0a0}.hn-editor-actions{display:flex;gap:10px;margin-top:12px}.hn-editor-actions button{flex:1;height:44px;border:1px solid rgba(229,189,98,.6);background:rgba(0,0,0,.34);color:var(--gold-light);font-size:9px;letter-spacing:.14em;text-transform:uppercase}.hn-editor-file{display:none!important}.hn-editor-back{width:100%;margin-top:14px}@media(max-width:520px){.hn-home-profile-button{width:57px;height:57px}.hn-editor-cover{height:155px}.hn-editor-avatar{left:18px;bottom:-48px;width:96px;height:96px}.hn-editor-content{padding-top:62px}.hn-editor-name{font-size:25px}}
.hn-family-profile-edit-hidden{display:none!important}`;document.head.appendChild(s)}
function renderMedia(root,r){const c=root?.querySelector('[data-cover]'),a=root?.querySelector('[data-avatar]');if(c)c.style.backgroundImage=r?.cover_path?`url("${media(r.cover_path)}")`:'';if(a)a.style.backgroundImage=r?.avatar_path?`url("${media(r.avatar_path)}")`:''}
async function compress(f,max){const b=await createImageBitmap(f),q=Math.min(1,max/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.max(1,b.width*q);c.height=Math.max(1,b.height*q);c.getContext('2d').drawImage(b,0,0,c.width,c.height);b.close?.();const z=await new Promise((ok,no)=>c.toBlob(x=>x?ok(x):no(Error('No fue posible preparar la imagen')),'image/webp',.84));return new File([z],Date.now()+'.webp',{type:'image/webp'})}
function stat(t,e=false){const x=edit?.querySelector('.hn-editor-status');if(x){x.textContent=t||'';x.className='hn-editor-status'+(e?' error':t?' success':'')}}
async function upload(type,file){const own=key(),p=F.find(x=>x[2]===own);if(!p)return;try{stat('Validando dispositivo…');await valid();stat('Preparando imagen…');const f=await compress(file,type==='avatar'?700:1800),local=URL.createObjectURL(f),target=edit.querySelector(type==='avatar'?'[data-avatar]':'[data-cover]');target.style.backgroundImage=`url("${local}")`;const fd=new FormData();fd.append('username',usr());fd.append('device_token',tok());fd.append('member_key',p[2]);fd.append('media_type',type);fd.append('file',f,f.name);const r=await fetch(M,{method:'POST',body:fd,cache:'no-store'});let d={};try{d=await r.json()}catch(_){}URL.revokeObjectURL(local);if(!r.ok||!d.ok)throw Error(d.error||'No fue posible guardar la imagen');renderMedia(edit,d.profile);refreshHomeAvatar();stat(type==='avatar'?'Foto de perfil actualizada.':'Foto de portada actualizada.');setTimeout(()=>stat(''),2500)}catch(e){console.error('[HN profile]',e);stat(e.message||'No fue posible guardar la imagen.',true)}}
function buildEditor(){if(edit)return;css();edit=document.createElement('section');edit.id='hnProfileEditor';edit.className='screen hn-profile-editor';edit.innerHTML=`<div class="hn-profile-editor-inner"><div class="hn-editor-cover" data-cover><button class="hn-editor-pencil hn-editor-cover-pencil" data-type="cover" type="button">✎</button><input class="hn-editor-file" data-file="cover" type="file" accept="image/jpeg,image/png,image/webp"><div class="hn-editor-avatar" data-avatar><button class="hn-editor-pencil hn-editor-avatar-pencil" data-type="avatar" type="button">✎</button><input class="hn-editor-file" data-file="avatar" type="file" accept="image/jpeg,image/png,image/webp"></div></div><div class="hn-editor-content"><h1 class="hn-editor-name"></h1><p class="hn-editor-role"></p><div class="hn-editor-status" aria-live="polite"></div><div class="hn-editor-actions"><button data-open="avatar" type="button">Foto de perfil</button><button data-open="cover" type="button">Foto de portada</button></div><button class="back-button hn-editor-back" type="button">Volver</button></div></div>`;$('.experience')?.append(edit);edit.querySelectorAll('.hn-editor-pencil').forEach(b=>b.onclick=()=>edit.querySelector(`[data-file="${b.dataset.type}"]`).click());edit.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>edit.querySelector(`[data-file="${b.dataset.open}"]`).click());edit.querySelectorAll('.hn-editor-file').forEach(i=>i.onchange=()=>{const f=i.files?.[0];i.value='';if(f)upload(i.dataset.file,f)});edit.querySelector('.hn-editor-back').onclick=()=>closeEditor(true)}
async function openEditor(back=false){if(!key())return;buildEditor();stat('');const p=F.find(x=>x[2]===key());edit.querySelector('.hn-editor-name').textContent=p[0];edit.querySelector('.hn-editor-role').textContent=p[1];renderMedia(edit,null);const r=await row(key()).catch(()=>null);if(r)renderMedia(edit,r);document.querySelectorAll('.screen').forEach(x=>x.classList.remove('is-active'));edit.classList.add('is-active');if(!back&&!he){history.pushState({hnEditor:true},'',location.href);he=true}}
function closeEditor(b=false){edit?.classList.remove('is-active');home()?.classList.add('is-active');if(b&&he){he=false;history.back()}else he=false}
function installHome(){const h=home(),top=h?.querySelector('.home-top');if(!h||!top||$('.hn-home-profile-wrap'))return;css();const old=[...top.querySelectorAll('button')].find(b=>/CERRAR\s+SESI[ÓO]N/i.test(b.textContent||''));const w=document.createElement('div');w.className='hn-home-profile-wrap';w.innerHTML='<button class="hn-home-profile-button" type="button" aria-label="Editar mi perfil"></button><span class="hn-home-profile-label">Mi perfil</span>';if(old)old.replaceWith(w);else top.append(w);w.querySelector('button').onclick=e=>{e.preventDefault();e.stopPropagation();openEditor()};if(old){old.classList.add('hn-home-logout-moved');const modules=h.querySelector('.modules');modules?.parentElement?.appendChild(old)}refreshHomeAvatar()}
async function refreshHomeAvatar(){const k=key();if(!k)return;const r=await row(k).catch(()=>null),b=$('.hn-home-profile-button');if(b)b.style.backgroundImage=r?.avatar_path?`url("${media(r.avatar_path)}")`:''}
function buildFamily(){if(fam)return;css();fam=document.createElement('section');fam.id='familyScreen';fam.className='screen family-screen';fam.innerHTML=`<div class="screen-inner family-inner"><div class="family-header"><p class="brand metallic-gold">HAVANA NICE</p><div class="brand-line"></div><p class="family-caption">The Family</p></div><div class="family-list">${F.map((p,i)=>`<button class="family-member" data-i="${i}" type="button"><span class="family-number">0${i+1}</span><span class="family-copy"><span class="family-name">${p[0]}</span><span class="family-role">${p[1]}</span></span><span class="family-arrow">›</span></button>`).join('')}</div><div class="family-footer"><button class="back-button" type="button">Volver</button></div></div>`;$('.experience')?.append(fam);fam.addEventListener('click',e=>{const b=e.target.closest('.family-member');if(b)openProfile(+b.dataset.i)});fam.querySelector('.back-button').onclick=()=>closeFamily(true)}
async function openProfile(i,pop=false){if(!prof){css();prof=document.createElement('section');prof.id='familyProfileScreen';prof.className='screen family-profile-screen';prof.innerHTML='<div class="family-profile-inner"><div class="family-profile-cover" data-cover><div class="family-profile-avatar" data-avatar></div></div><div class="family-profile-content"><h1 class="family-profile-name"></h1><p class="family-profile-role"></p><section class="family-profile-bio-box"><h2 class="family-profile-bio-title">BIOGRAFÍA</h2><div class="family-profile-bio"></div></section><button class="back-button family-profile-back" type="button">Volver</button></div></div>';$('.experience')?.append(prof);prof.querySelector('.family-profile-back').onclick=()=>closeProfile(true)}prof.dataset.i=i;const p=F[i];prof.querySelector('.family-profile-name').textContent=p[0];prof.querySelector('.family-profile-role').textContent=p[1];prof.querySelector('.family-profile-bio').innerHTML='<span class="family-profile-placeholder">Espacio reservado para la biografía</span>';renderMedia(prof,null);document.querySelectorAll('.screen').forEach(x=>x.classList.remove('is-active'));prof.classList.add('is-active');const r=await row(p[2]).catch(()=>null);if(r){renderMedia(prof,r);prof.querySelector('.family-profile-bio').innerHTML=r.bio?String(r.bio).replace(/\n/g,'<br>'):'<span class="family-profile-placeholder">Espacio reservado para la biografía</span>'}if(!pop&&!hp){history.pushState({hnProfile:true,index:i},'',location.href);hp=true}}
function closeProfile(b=false){prof?.classList.remove('is-active');fam?.classList.add('is-active');if(b&&hp){hp=false;history.back()}else hp=false}
function closeFamily(b=false){fam?.classList.remove('is-active');(prev||home())?.classList.add('is-active');if(b&&hf){hf=false;history.back()}else hf=false}
function openFamily(){buildFamily();prev=$('.screen.is-active');document.querySelectorAll('.screen').forEach(x=>x.classList.remove('is-active'));fam.classList.add('is-active');if(!hf){history.pushState({hnFamily:true},'',location.href);hf=true}ensureRT()}
function ensureRT(){if(ch||!sb)return;ch=sb.channel('family-profiles-live').on('postgres_changes',{event:'*',schema:'public',table:'family_profiles'},p=>{const r=p.new;if(!r?.member_key)return;if(prof?.classList.contains('is-active')&&F[+prof.dataset.i]?.[2]===r.member_key)renderMedia(prof,r);if(edit?.classList.contains('is-active')&&r.member_key===key())renderMedia(edit,r);if(r.member_key===key())refreshHomeAvatar()}).subscribe()}
function init(){const mods=$('.modules');if(!mods)return;const b=[...mods.querySelectorAll('.module')].find(x=>/FAMILIA|MÚSICOS|MUSICOS/i.test(x.textContent||''));if(b)b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openFamily()},true);installHome();db().then(c=>{sb=c;ensureRT();refreshHomeAvatar()}).catch(console.error);window.addEventListener('popstate',()=>{if(edit?.classList.contains('is-active'))closeEditor();else if(prof?.classList.contains('is-active'))closeProfile();else if(fam?.classList.contains('is-active'))closeFamily()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else setTimeout(init,0);
})();