/* HAVANA NICE — NOTIFICATIONS / SERVER-FIRST STATE */
(function(){
'use strict';
var client=null,channel=null,started=false,reconnectTimer=null,sessionPollTimer=null,pollTimer=null;
var notifications=[],readIds=new Set(),ready=false,module=null,subtitle=null,badge=null;
var READ_KEY='hn_notifications_read_v2';
function logged(){return !!sessionStorage.getItem('hn_profile')}
function getClient(){return window.hnSupabase&&typeof window.hnSupabase.channel==='function'?window.hnSupabase:null}
function style(){if(document.getElementById('hnNotifyV5Style'))return;var s=document.createElement('style');s.id='hnNotifyV5Style';s.textContent='.hn-notify-badge{position:absolute;top:10px;right:12px;min-width:24px;height:24px;padding:0 7px;border:1px solid #fff1a8;border-radius:999px;background:#e5bd62;color:#020302;display:none;align-items:center;justify-content:center;font:600 11px Arial,sans-serif;z-index:3}.hn-notify-badge.hn-notify-badge-visible{display:flex}.hn-notify-loading .hn-notify-badge{display:none!important}.hn-notify-screen{overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;touch-action:pan-y!important;box-sizing:border-box!important;height:100%!important;max-height:100%!important;padding-bottom:40px!important}.hn-notify-screen .hn-n-image{display:block!important;width:auto!important;height:auto!important;max-width:100%!important;max-height:70vh!important;object-fit:contain!important;margin:14px auto!important;border-radius:0!important}.hn-notify-screen .hn-n-item{height:auto!important;min-height:0!important}.hn-notify-screen .hn-n-date{margin-bottom:10px!important}';document.head.appendChild(s)}
function find(){if(module&&document.body.contains(module))return;module=null;subtitle=null;badge=null;document.querySelectorAll('.module').forEach(function(m){var t=m.querySelector('.module-title');if(t&&t.textContent.trim().toUpperCase()==='NOTIFICACIONES'){module=m;subtitle=m.querySelector('.module-subtitle');module.style.position='relative';badge=m.querySelector('.hn-notify-badge');if(!badge){badge=document.createElement('span');badge.className='hn-notify-badge';module.appendChild(badge)}}})}
function count(){if(!ready)return 0;var n=0;notifications.forEach(function(x){if(x&&x.id&&!readIds.has(x.id))n++});return n}
function appBadge(n){try{if(n&&navigator.setAppBadge)navigator.setAppBadge(Math.min(99,n));else if(!n&&navigator.clearAppBadge)navigator.clearAppBadge()}catch(_) {}}
function paint(){find();if(!ready){if(badge)badge.classList.remove('hn-notify-badge-visible');appBadge(0);return}var n=count();if(subtitle)subtitle.textContent=notifications.length?(notifications.length===1?'1 notificación':notifications.length+' notificaciones'):'Sin notificaciones';if(badge){badge.textContent=n>99?'99+':String(n);badge.classList.toggle('hn-notify-badge-visible',n>0)}appBadge(n)}
function loadRead(){try{var x=JSON.parse(localStorage.getItem(READ_KEY)||'[]');if(Array.isArray(x))readIds=new Set(x)}catch(_) {readIds=new Set()}}
function saveRead(){try{localStorage.setItem(READ_KEY,JSON.stringify(Array.from(readIds)))}catch(_) {}}
function markRead(){notifications.forEach(function(x){if(x&&x.id)readIds.add(x.id)});saveRead();paint()}
function render(){var screen=document.getElementById('moduleScreen');if(!screen)return;var inner=screen.querySelector('.screen-inner');if(!inner)return;inner.className='screen-inner coming-screen hn-notify-screen';inner.innerHTML='';var b=document.createElement('p');b.className='brand metallic-gold';b.textContent='HAVANA NICE';inner.appendChild(b);var line=document.createElement('div');line.className='brand-line';inner.appendChild(line);var h=document.createElement('div');h.className='hn-n-head';h.textContent='Notifications';inner.appendChild(h);var list=document.createElement('div');if(!notifications.length){var e=document.createElement('div');e.className='hn-n-empty';e.textContent='No notifications';list.appendChild(e)}else notifications.forEach(function(x){var a=document.createElement('article');a.className='hn-n-item'+(readIds.has(x.id)?'':' hn-n-unread');var t=document.createElement('div');t.className='hn-n-title';t.textContent=x.title||'Notification';a.appendChild(t);var m=document.createElement('div');m.className='hn-n-message';m.textContent=x.message||'';a.appendChild(m);var urls=Array.isArray(x.image_urls)&&x.image_urls.length?x.image_urls:(x.image_url?[x.image_url]:[]);urls.slice(0,3).forEach(function(u){if(!u)return;var im=document.createElement('img');im.className='hn-n-image';im.src=u;im.alt='Imagen de notificación';im.loading='lazy';a.appendChild(im)});var d=document.createElement('div');d.className='hn-n-date';d.textContent=x.created_at?new Date(x.created_at).toLocaleString():'';a.appendChild(d);list.appendChild(a)});inner.appendChild(list);var back=document.createElement('button');back.className='back-button hn-n-back';back.type='button';back.textContent='Volver';back.onclick=function(){var ms=document.getElementById('moduleScreen'),home=document.getElementById('homeScreen');if(ms)ms.classList.remove('is-active');if(home)home.classList.add('is-active')};inner.appendChild(back)}
function open(){if(!ready)return;markRead();render();var ms=document.getElementById('moduleScreen'),home=document.getElementById('homeScreen'),login=document.getElementById('loginScreen'),rep=document.getElementById('repertoireScreen');if(login)login.classList.remove('is-active');if(home)home.classList.remove('is-active');if(rep)rep.classList.remove('is-active');if(ms)ms.classList.add('is-active');appBadge(0)}
function flash(){find();if(!module)return;module.classList.remove('hn-notify-flash');void module.offsetWidth;module.classList.add('hn-notify-flash');setTimeout(paint,3200)}
async function sync(showFlash){if(!client||!logged())return;try{var r=await client.from('notifications').select('id,title,message,image_url,image_urls,created_at').order('created_at',{ascending:false}).limit(50);if(r.error){console.error('[HN-Notifications] sync error',r.error);return}var server=r.data||[],old=new Set(notifications.map(function(x){return x&&x.id}).filter(Boolean));var added=server.some(function(x){return x&&x.id&&!old.has(x.id)});notifications=server;var ids=new Set(server.map(function(x){return x&&x.id}).filter(Boolean));readIds.forEach(function(id){if(!ids.has(id))readIds.delete(id)});saveRead();ready=true;paint();var ms=document.getElementById('moduleScreen');if(ms&&ms.classList.contains('is-active')&&ms.querySelector('.hn-notify-screen'))render();if(showFlash&&added)flash()}catch(e){console.error('[HN-Notifications] sync exception',e)}}
function subscribe(){if(!client)return;if(channel){try{client.removeChannel(channel)}catch(_) {}}channel=client.channel('hn-notifications-realtime').on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications'},function(){sync(true)}).on('postgres_changes',{event:'DELETE',schema:'public',table:'notifications'},function(){sync(false)}).subscribe(function(st){if(st==='SUBSCRIBED')sync(false);else if(st==='CHANNEL_ERROR'||st==='TIMED_OUT'||st==='CLOSED'){clearTimeout(reconnectTimer);reconnectTimer=setTimeout(function(){if(started)subscribe()},2500)}})}
function stop(){started=false;clearTimeout(reconnectTimer);if(channel){try{client.removeChannel(channel)}catch(_) {}}channel=null;clearInterval(pollTimer);notifications=[];ready=false;appBadge(0);paint()}
function start(){if(started)return;client=getClient();if(!client||!logged())return;started=true;ready=false;notifications=[];loadRead();document.documentElement.classList.add('hn-notify-loading');paint();sync(false);subscribe();clearInterval(pollTimer);pollTimer=setInterval(function(){sync(false)},30000)}
function watch(){clearInterval(sessionPollTimer);sessionPollTimer=setInterval(function(){if(logged())start();else if(started)stop()},5000)}
function init(){style();find();document.addEventListener('click',function(e){var m=e.target.closest&&e.target.closest('.module');if(!m)return;var t=m.querySelector('.module-title');if(t&&t.textContent.trim().toUpperCase()==='NOTIFICACIONES'){e.preventDefault();e.stopImmediatePropagation();open()}},true);start();watch();document.addEventListener('visibilitychange',function(){if(!document.hidden&&started)sync(false)});window.addEventListener('online',function(){if(started)sync(false)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
import('./musician-push.js?v=8161dc96f20726250add287b26d2614b9cf42bdc').catch(function(){});
