(function () {
  'use strict';
  var client=null,channel=null,started=false,reconnectTimer=null,sessionPollTimer=null,notificationPollTimer=null;
  var notifications=[],seenIds=new Set(),readIds=new Set(),notificationModule=null,notificationSubtitle=null,notificationBadge=null;
  var STORAGE_KEY='hn_notifications_cache_v1',READ_STORAGE_KEY='hn_notifications_read_v1';
  function isLoggedIn(){return !!sessionStorage.getItem('hn_profile')}
  function getClient(){return window.hnSupabase&&typeof window.hnSupabase.channel==='function'?window.hnSupabase:null}
  function addStyle(){if(document.getElementById('hnNotifyStyle'))return;var style=document.createElement('style');style.id='hnNotifyStyle';style.textContent=['.hn-notify-flash{animation:hnNotifyFlash 1.2s ease-in-out 0s 2}','@keyframes hnNotifyFlash{0%,100%{box-shadow:0 0 0 rgba(229,189,98,0)}50%{box-shadow:0 0 28px rgba(229,189,98,.5),inset 0 0 20px rgba(229,189,98,.08)}}','.hn-notify-new{color:#fff1a8!important;opacity:1!important}','.hn-notify-screen{height:100%!important;max-height:100%;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;box-sizing:border-box;padding-bottom:110px!important}','.hn-notify-screen .hn-n-head{margin-top:24px;padding:0 0 18px;border-bottom:1px solid rgba(229,189,98,.25);font:14px Georgia,serif;letter-spacing:.18em;color:#fff1a8;text-transform:uppercase}','.hn-notify-screen .hn-n-item{padding:19px 0;border-bottom:1px solid rgba(255,255,255,.09);border-left:2px solid transparent;padding-left:12px;margin-left:-14px;transition:background .25s ease,border-color .25s ease}','.hn-notify-screen .hn-n-item.hn-n-unread{border-left-color:#e5bd62;background:linear-gradient(90deg,rgba(229,189,98,.10),transparent 75%)}','.hn-notify-screen .hn-n-item.hn-n-unread .hn-n-title{text-decoration:underline;text-decoration-color:#e5bd62;text-decoration-thickness:1px;text-underline-offset:5px}','.hn-notify-screen .hn-n-item.hn-n-unread .hn-n-date{color:rgba(229,189,98,.72)}','.hn-notify-screen .hn-n-title{color:#f4f1e8;font-size:12px;letter-spacing:.12em;text-transform:uppercase}','.hn-notify-screen .hn-n-message{margin-top:9px;color:rgba(244,241,232,.78);font-size:13px;line-height:1.55;white-space:pre-wrap}','.hn-notify-screen .hn-n-image{display:block;width:100%;max-height:280px;object-fit:cover;margin-top:13px;border:1px solid rgba(229,189,98,.22)}','.hn-notify-screen .hn-n-date{margin-top:9px;color:rgba(244,241,232,.38);font-size:8px;letter-spacing:.12em;text-transform:uppercase}','.hn-notify-screen .hn-n-empty{padding:34px 0;color:rgba(244,241,232,.42);font-size:10px;letter-spacing:.12em;text-transform:uppercase;text-align:center}','.hn-notify-screen .hn-n-back{display:block;margin:28px 0 20px;position:relative;z-index:5;pointer-events:auto}','.hn-notify-badge{position:absolute;top:10px;right:12px;min-width:24px;height:24px;padding:0 7px;border:1px solid #fff1a8;border-radius:999px;background:#e5bd62;color:#020302;display:none;align-items:center;justify-content:center;font:600 11px Arial,sans-serif;letter-spacing:0;box-shadow:0 0 16px rgba(229,189,98,.35);z-index:3}','.hn-notify-badge.hn-notify-badge-visible{display:flex}'].join('');document.head.appendChild(style)}
  function makeElement(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
  function findNotificationModule(){if(notificationModule&&document.body.contains(notificationModule))return notificationModule;notificationModule=null;notificationSubtitle=null;notificationBadge=null;var modules=document.querySelectorAll('.module');for(var i=0;i<modules.length;i++){var title=modules[i].querySelector('.module-title');if(title&&title.textContent.trim().toUpperCase()==='NOTIFICACIONES'){notificationModule=modules[i];notificationSubtitle=modules[i].querySelector('.module-subtitle');notificationModule.style.position='relative';notificationBadge=notificationModule.querySelector('.hn-notify-badge');if(!notificationBadge){notificationBadge=makeElement('span','hn-notify-badge');notificationBadge.setAttribute('aria-label','Notificaciones nuevas');notificationModule.appendChild(notificationBadge)}break}}return notificationModule}
  function unreadCount(){var count=0;notifications.forEach(function(item){if(item&&item.id&&!readIds.has(item.id))count++});return count}
  function setAppBadge(value){try{if(value>0&&typeof navigator.setAppBadge==='function')navigator.setAppBadge(Math.min(99,value));else if(value===0&&typeof navigator.clearAppBadge==='function')navigator.clearAppBadge()}catch(_){}}
  function clearAppBadge(){try{if(typeof navigator.clearAppBadge==='function')navigator.clearAppBadge();else if(typeof navigator.setAppBadge==='function')navigator.setAppBadge(0)}catch(_) {}}
  function updateModule(){findNotificationModule();var unread=unreadCount();if(notificationSubtitle)notificationSubtitle.textContent=notifications.length?(notifications.length===1?'1 notificación':notifications.length+' notificaciones'):'Sin notificaciones';if(notificationBadge){notificationBadge.textContent=unread>99?'99+':String(unread);notificationBadge.classList.toggle('hn-notify-badge-visible',unread>0)}setAppBadge(unread)}
  function flashModule(){findNotificationModule();if(!notificationModule)return;notificationModule.classList.remove('hn-notify-flash');void notificationModule.offsetWidth;notificationModule.classList.add('hn-notify-flash');if(notificationSubtitle){notificationSubtitle.textContent='NUEVA NOTIFICACIÓN';notificationSubtitle.classList.add('hn-notify-new')}setTimeout(function(){if(notificationSubtitle)notificationSubtitle.classList.remove('hn-notify-new');updateModule()},3200)}
  function saveCache(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(notifications.slice(0,50)))}catch(_) {}}
  function saveReadIds(){try{localStorage.setItem(READ_STORAGE_KEY,JSON.stringify(Array.from(readIds)))}catch(_) {}}
  function loadCache(){try{var raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;var cached=JSON.parse(raw);if(!Array.isArray(cached))return;notifications=[];seenIds.clear();cached.forEach(function(item){if(!item||!item.id||seenIds.has(item.id))return;seenIds.add(item.id);notifications.push(item)});notifications.sort(function(a,b){return new Date(b.created_at||0)-new Date(a.created_at||0)});updateModule()}catch(_) {}}
  function loadReadIds(){try{var raw=localStorage.getItem(READ_STORAGE_KEY);if(!raw)return;var stored=JSON.parse(raw);if(Array.isArray(stored))readIds=new Set(stored)}catch(_) {}}
  function markAllRead(){notifications.forEach(function(item){if(item&&item.id)readIds.add(item.id)});saveReadIds();updateModule()}
  function restoreGenericModuleScreen(){var screen=document.getElementById('moduleScreen');if(!screen)return;var inner=screen.querySelector('.screen-inner');if(!inner||!inner.classList.contains('hn-notify-screen'))return;inner.className='screen-inner coming-screen';inner.innerHTML='';inner.appendChild(makeElement('p','brand metallic-gold','HAVANA NICE'));inner.appendChild(makeElement('div','brand-line'));inner.appendChild(makeElement('h2','coming-title metallic-gold','PRÓXIMAMENTE'));inner.appendChild(makeElement('p','coming-copy','Esta sección estará disponible próximamente'));var back=makeElement('button','back-button','Volver');back.type='button';back.addEventListener('click',function(event){event.preventDefault();event.stopPropagation();var moduleScreen=document.getElementById('moduleScreen'),home=document.getElementById('homeScreen'),login=document.getElementById('loginScreen'),repertoire=document.getElementById('repertoireScreen');if(moduleScreen)moduleScreen.classList.remove('is-active');if(repertoire)repertoire.classList.remove('is-active');if(login)login.classList.remove('is-active');if(home)home.classList.add('is-active')});inner.appendChild(back)}
  function bindGenericModules(){document.addEventListener('click',function(event){var module=event.target.closest('.module[data-module]');if(!module)return;var title=module.querySelector('.module-title');if(!title)return;if(title.textContent.trim().toUpperCase()!=='NOTIFICACIONES')restoreGenericModuleScreen()},true)}
  function renderNotificationScreen(){var screen=document.getElementById('moduleScreen');if(!screen)return;var inner=screen.querySelector('.screen-inner');if(!inner)return;inner.className='screen-inner coming-screen hn-notify-screen';inner.innerHTML='';inner.appendChild(makeElement('p','brand metallic-gold','HAVANA NICE'));inner.appendChild(makeElement('div','brand-line'));inner.appendChild(makeElement('div','hn-n-head','Notifications'));var list=makeElement('div');if(!notifications.length)list.appendChild(makeElement('div','hn-n-empty','No notifications'));else notifications.forEach(function(item){var unread=!readIds.has(item.id),article=makeElement('article','hn-n-item'+(unread?' hn-n-unread':''));article.appendChild(makeElement('div','hn-n-title',String(item.title||'Notification')));article.appendChild(makeElement('div','hn-n-message',String(item.message||'')));var imageUrls=Array.isArray(item.image_urls)?item.image_urls:(item.image_url?[item.image_url]:[]);imageUrls.slice(0,3).forEach(function(url){if(!url)return;var image=makeElement('img','hn-n-image');image.src=String(url);image.alt='Imagen de notificación';image.loading='lazy';image.decoding='async';article.appendChild(image)})article.appendChild(makeElement('div','hn-n-date',item.created_at?new Date(item.created_at).toLocaleString():''));list.appendChild(article)});inner.appendChild(list);var back=makeElement('button','back-button hn-n-back','Volver');back.type='button';back.addEventListener('click',function(event){event.preventDefault();event.stopPropagation();clearAppBadge();var moduleScreen=document.getElementById('moduleScreen'),home=document.getElementById('homeScreen'),login=document.getElementById('loginScreen'),repertoire=document.getElementById('repertoireScreen');if(moduleScreen)moduleScreen.classList.remove('is-active');if(repertoire)repertoire.classList.remove('is-active');if(login)login.classList.remove('is-active');if(home)home.classList.add('is-active')});inner.appendChild(back)}
  function openNotifications(){if(!isLoggedIn())return;renderNotificationScreen();markAllRead();renderNotificationScreen();clearAppBadge();var screen=document.getElementById('moduleScreen'),home=document.getElementById('homeScreen'),login=document.getElementById('loginScreen'),repertoire=document.getElementById('repertoireScreen');if(login)login.classList.remove('is-active');if(home)home.classList.remove('is-active');if(repertoire)repertoire.classList.remove('is-active');if(screen)screen.classList.add('is-active')}
  function bindModule(){findNotificationModule();if(!notificationModule||notificationModule.dataset.hnNotifyBound==='true')return;notificationModule.dataset.hnNotifyBound='true';notificationModule.addEventListener('click',function(event){event.preventDefault();event.stopImmediatePropagation();try{if(typeof window.playClickSound==='function')window.playClickSound()}catch(_){}openNotifications()},true)}
  function mergeItems(items,showFlash){if(!Array.isArray(items))return false;var added=[];items.forEach(function(item){if(!item||!item.id||seenIds.has(item.id))return;seenIds.add(item.id);added.push(item)});if(!added.length)return false;notifications=notifications.concat(added);notifications.sort(function(a,b){return new Date(b.created_at||0)-new Date(a.created_at||0)});notifications=notifications.slice(0,50);saveCache();updateModule();if(showFlash)flashModule();return true}
  function reconcileWithServer(serverItems){if(!Array.isArray(serverItems))return false;var serverIds=new Set(serverItems.map(function(item){return item&&item.id}).filter(Boolean)),before=notifications.length;notifications=notifications.filter(function(item){return item&&serverIds.has(item.id)});if(notifications.length===before)return false;seenIds.clear();notifications.forEach(function(item){seenIds.add(item.id)});readIds.forEach(function(id){if(!seenIds.has(id))readIds.delete(id)});saveCache();saveReadIds();renderNotificationScreenIfOpen();updateModule();return true}
  function removeNotification(id){if(!id)return;var changed=false;notifications=notifications.filter(function(item){if(item&&item.id===id){changed=true;return false}return true});if(!changed)return;seenIds.delete(id);readIds.delete(id);saveCache();saveReadIds();renderNotificationScreenIfOpen();updateModule()}
  function renderNotificationScreenIfOpen(){var screen=document.getElementById('moduleScreen');if(screen&&screen.classList.contains('is-active')&&screen.querySelector('.hn-notify-screen'))renderNotificationScreen()}
  async function syncRecent(showFlash){if(!client||!isLoggedIn())return;try{var result=await client.from('notifications').select('id,title,message,image_url,image_urls,created_at').order('created_at',{ascending:false}).limit(50);if(result.error){console.error('[HN-Notifications] sync error:',result.error);return}var serverItems=result.data||[];var known=new Set(notifications.map(function(item){return item&&item.id}).filter(Boolean));var newItems=serverItems.filter(function(item){return item&&item.id&&!known.has(item.id)});reconcileWithServer(serverItems);mergeItems(newItems,showFlash)}catch(error){console.error('[HN-Notifications] sync exception:',error)}}
  function subscribe(){if(!client)return;if(channel){try{client.removeChannel(channel)}catch(_){}}channel=client.channel('hn-notifications-realtime').on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications'},function(payload){mergeItems([payload.new],true)}).on('postgres_changes',{event:'DELETE',schema:'public',table:'notifications'},function(payload){removeNotification(payload.old&&payload.old.id)}).subscribe(function(status){if(status==='SUBSCRIBED')syncRecent(false);else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){if(reconnectTimer)clearTimeout(reconnectTimer);reconnectTimer=setTimeout(function(){if(started)subscribe()},2500)}})}
  function stop(){started=false;if(reconnectTimer)clearTimeout(reconnectTimer);reconnectTimer=null;if(channel){try{client.removeChannel(channel)}catch(_){}}channel=null;if(notificationPollTimer)clearInterval(notificationPollTimer);notificationPollTimer=null;notifications=[];seenIds.clear();updateModule()}
  function start(){if(started)return;client=getClient();if(!client||!isLoggedIn())return;started=true;loadReadIds();loadCache();syncRecent(false);subscribe();notificationPollTimer=setInterval(function(){syncRecent(false)},5000)}
  function watchSession(){if(sessionPollTimer)clearInterval(sessionPollTimer);sessionPollTimer=setInterval(function(){if(isLoggedIn())start();else if(started)stop()},1000)}
  function init(){addStyle();bindModule();bindGenericModules();start();watchSession();window.addEventListener('online',function(){if(started)syncRecent(false)});document.addEventListener('visibilitychange',function(){if(!document.hidden&&started)syncRecent(false)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
