const HN_SUPABASE='https://xzfradccsxonmauinecl.supabase.co';
const HN_KEY='sb_publishable_Ip5rGK0UVXIfOjs_RQ_LhA_c14foHN9';
const HN_API=HN_SUPABASE+'/rest/v1/notifications?select=id,title,message,created_at&order=created_at.desc';
const state={items:[],ready:false};
const esc=v=>String(v??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
function inject(){if(document.getElementById('hnNotificationsRoot'))return;const s=document.createElement('style');s.textContent='#hnNotificationsRoot{position:fixed;right:18px;top:74px;z-index:99999;font-family:Arial,sans-serif}#hnNotifyButton{width:46px;height:46px;border:1px solid rgba(229,189,98,.72);background:rgba(0,0,0,.72);color:#fff1a8;border-radius:50%;font-size:18px;position:relative;cursor:pointer;box-shadow:0 8px 30px rgba(0,0,0,.35)}#hnNotifyCount{position:absolute;right:-3px;top:-4px;min-width:17px;height:17px;padding:0 4px;border-radius:10px;background:#e5bd62;color:#020302;font:700 9px/17px Arial;text-align:center;display:none}#hnNotifyPanel{position:fixed;right:18px;top:132px;width:min(350px,calc(100vw - 36px));max-height:65vh;overflow:auto;border:1px solid rgba(229,189,98,.65);background:rgba(2,3,2,.97);display:none;box-shadow:0 18px 60px rgba(0,0,0,.55)}#hnNotifyPanel.open{display:block}.hn-n-head{padding:18px;border-bottom:1px solid rgba(229,189,98,.22);font:14px Georgia,serif;letter-spacing:.18em;color:#fff1a8;text-transform:uppercase}.hn-n-item{padding:17px 18px;border-bottom:1px solid rgba(255,255,255,.08)}.hn-n-title{color:#f4f1e8;font-size:12px;letter-spacing:.12em;text-transform:uppercase}.hn-n-message{margin-top:8px;color:rgba(244,241,232,.72);font-size:12px;line-height:1.5}.hn-n-date{margin-top:9px;color:rgba(244,241,232,.36);font-size:8px;letter-spacing:.12em;text-transform:uppercase}.hn-n-empty{padding:24px 18px;color:rgba(244,241,232,.42);font-size:10px;letter-spacing:.12em;text-transform:uppercase;text-align:center}#hnNotifyToast{position:fixed;left:50%;bottom:92px;transform:translate(-50%,20px);width:min(390px,calc(100vw - 36px));padding:16px 18px;border:1px solid rgba(229,189,98,.7);background:rgba(2,3,2,.96);color:#f4f1e8;opacity:0;pointer-events:none;transition:opacity .3s,transform .3s;z-index:100000}#hnNotifyToast.show{opacity:1;transform:translate(-50%,0)}#hnNotifyToast strong{display:block;color:#fff1a8;font-size:11px;letter-spacing:.12em;text-transform:uppercase}.hn-toast-msg{margin-top:6px;font-size:11px;line-height:1.45;color:rgba(244,241,232,.72)}';document.head.appendChild(s);const r=document.createElement('div');r.id='hnNotificationsRoot';r.style.display='none';r.innerHTML='<button id="hnNotifyButton" aria-label="Notifications">♢<span id="hnNotifyCount"></span></button><div id="hnNotifyPanel"><div class="hn-n-head">Notifications</div><div id="hnNotifyList"></div></div><div id="hnNotifyToast"></div>';document.body.appendChild(r);document.getElementById('hnNotifyButton').onclick=()=>document.getElementById('hnNotifyPanel').classList.toggle('open')}
function render(){const l=document.getElementById('hnNotifyList'),c=document.getElementById('hnNotifyCount');if(!l)return;c.textContent=state.items.length>99?'99+':state.items.length;c.style.display=state.items.length?'block':'none';l.innerHTML=state.items.length?state.items.map(n=>`<article class="hn-n-item"><div class="hn-n-title">${esc(n.title)}</div><div class="hn-n-message">${esc(n.message)}</div><div class="hn-n-date">${new Date(n.created_at).toLocaleString()}</div></article>`).join(''):'<div class="hn-n-empty">No notifications</div>'}
function toast(n){const t=document.getElementById('hnNotifyToast');if(!t)return;t.innerHTML=`<strong>${esc(n.title)}</strong><div class="hn-toast-msg">${esc(n.message)}</div>`;t.classList.add('show');clearTimeout(window.__hnToastTimer);window.__hnToastTimer=setTimeout(()=>t.classList.remove('show'),4500)}
async function load(){try{const r=await fetch(HN_API,{headers:{apikey:HN_KEY,Authorization:'Bearer '+HN_KEY,Accept:'application/json'},cache:'no-store'});if(!r.ok)return;const data=await r.json();const old=state.items[0]?.id;state.items=Array.isArray(data)?data:[];render();if(old&&state.items[0]&&old!==state.items[0].id)toast(state.items[0])}catch(e){console.error('HN notifications:',e)}}
function syncVisibility(){const logged=!!sessionStorage.getItem('hn_profile');const r=document.getElementById('hnNotificationsRoot');if(r)r.style.display=logged?'block':'none';if(logged&&!state.ready){state.ready=true;load()}}
inject();syncVisibility();setInterval(()=>{syncVisibility();if(state.ready)load()},2000);