/* HAVANA NICE — OPERATIONS UI FIX */
(function(){'use strict';function installDeviceGate(){const b=document.getElementById('loginButton'),i=document.getElementById('username');if(!b||!i||b.dataset.hnDeviceGate==='1')return;b.dataset.hnDeviceGate='1';let busy=false;const msg=t=>{const e=document.getElementById('loginMessage');if(e)e.textContent=t||''};async function h(){if(busy)return;const u=i.value.trim();if(!u){msg('Escribe tu nombre');return}busy=true;b.disabled=true;msg('Verificando acceso...');try{const m=await import('./musician-device-access-v1.js?v=180733417c2b7f261249394d43ba1b1c4a82b1af6'),r=await m.requestAccess(u);if(r.status==='authorized'){const p=r.profile,s={id:p.id,username:p.username,role:p.role};sessionStorage.setItem('hn_profile',JSON.stringify(s));try{localStorage.setItem('hn_last_musician_v1',JSON.stringify(s))}catch(_){}document.getElementById('welcomeName')&&(document.getElementById('welcomeName').textContent=p.username||'');document.getElementById('welcomeRole')&&(document.getElementById('welcomeRole').textContent=p.role||'Músico de HAVANA NICE');document.getElementById('loginScreen')?.classList.remove('is-active');document.getElementById('homeScreen')?.classList.add('is-active');window.dispatchEvent(new CustomEvent('hn:session-ready',{detail:s}));msg('');return}msg(r.status==='pending'?'Acceso pendiente de autorización del administrador':r.message||'Acceso no autorizado')}catch(e){console.error(e);msg('No fue posible verificar el acceso')}finally{b.disabled=false;busy=false}}b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();h()},true);i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();b.click()}},true)}
function init(){document.getElementById('hnMyDay')?.remove();const s=document.createElement('style');s.textContent='.hn-showday-action{display:block;width:100%;margin-top:11px;padding:12px 13px;border:1px solid rgba(229,189,98,.62);border-radius:12px;color:#fff1a8;background:rgba(0,0,0,.24);font-size:9px;letter-spacing:.18em;text-transform:uppercase;cursor:pointer}.module,.hn-chat-module,.calendar-event-card,.hn-chat-bubble,.hn-chat-input,.hn-chat-send,.hn-chat-recording,.hn-chat-pending-item,.hn-chat-media-item{border-radius:12px!important}';document.head.appendChild(s);installDeviceGate();if(!document.getElementById('hnChatMediaLightboxScript')){const x=document.createElement('script');x.id='hnChatMediaLightboxScript';x.src='./chat-media-lightbox-v2.js?v=0d450ca2b0d7331852c10c889e4cc59f7da2d4ea';document.body.appendChild(x)}if(!document.getElementById('hnChatVideoControlsScript')){const x=document.createElement('script');x.id='hnChatVideoControlsScript';x.src='./chat-video-controls-v1.js?v=0f538e980d6ce8bc2ac5f89d08541478316b1ba2';document.body.appendChild(x)}if(!document.getElementById('hnMusicianBackgroundScript')){const x=document.createElement('script');x.id='hnMusicianBackgroundScript';x.src='./musician-background-v1.js?v=ec04a9e0e86e09e9a3c45df501957b282c8297ec';document.body.appendChild(x)}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()})();
(function(){var s=document.createElement('script');s.src='./session-memory-v2.js?v=20260916-stable';s.async=false;document.head.appendChild(s)})();
(function(){var s=document.createElement('script');s.src='./chat-typing-v2.js?v=70a94193937be7ab27a714e00fde8efe34503edb';s.async=false;document.head.appendChild(s)})();
(function(){var s=document.createElement('script');s.src='./chat-realtime-guard-v1.js?v=7edbf360d985a8ce064d8bd2f04d68b5aa026d62';s.async=false;document.head.appendChild(s)})();
(function(){var s=document.createElement('script');s.src='./ios-install-v1.js?v=1';s.async=false;document.head.appendChild(s)})();
(function(){var s=document.createElement('script');s.src='./chat-media-fix-v1.js?v=5cf352ffc30cd1146893f05b10fc57dcd4e080b2';s.async=false;document.head.appendChild(s)})();
(function(){var s=document.createElement('script');s.src='./chat-keyboard-v1.js?v=9264af2797639e7b263bd754b82a76caece56c58';s.async=false;document.head.appendChild(s)})();
(function(){var s=document.createElement('script');s.src='./family-profile-data-v2.js?v=473935bbb856e4425e5752c24a5b14d05a2b1498';s.async=false;document.head.appendChild(s)})();