/* HAVANA NICE — PASSKEY CLIENT */
(function(){'use strict';
var BASE='https://xzfradccsxonmauinecl.supabase.co/functions/v1/';
var USER_KEY='app-passkey-user-id',CRED_KEY='app-passkey-credential-id',EN_KEY='app-passkey-enabled';
function supported(){return !!(window.PublicKeyCredential&&navigator.credentials&&navigator.credentials.get&&navigator.credentials.create)}
function getSaved(){try{return {user:localStorage.getItem(USER_KEY)||'',cred:localStorage.getItem(CRED_KEY)||'',enabled:localStorage.getItem(EN_KEY)==='1'}}catch(_){return {user:'',cred:'',enabled:false}}}
function save(x){try{if(x.user)localStorage.setItem(USER_KEY,x.user);if(x.credentialId)localStorage.setItem(CRED_KEY,x.credentialId);localStorage.setItem(EN_KEY,'1')}catch(_) {}}
function clear(){try{localStorage.removeItem(USER_KEY);localStorage.removeItem(CRED_KEY);localStorage.removeItem(EN_KEY)}catch(_) {}}
function b64url(buf){var a=new Uint8Array(buf),s='';for(var i=0;i<a.length;i++)s+=String.fromCharCode(a[i]);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function from64(s){var t=s.replace(/-/g,'+').replace(/_/g,'/');while(t.length%4)t+='=';var b=atob(t),a=new Uint8Array(b.length);for(var i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a.buffer}
function json(x){return x&&typeof x==='object'?x:{}}
async function post(name,body){var c=new AbortController(),timer=setTimeout(function(){c.abort()},8000);try{var r=await fetch(BASE+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{}),signal:c.signal});var d=await r.json().catch(function(){return {}});if(!r.ok)throw new Error(d.error||'Server error');return d}finally{clearTimeout(timer)}}
function setMessage(s){var e=document.querySelector('.login-message');if(e)e.textContent=s||''}
async function login(){if(!supported())return;var saved=getSaved();if(!saved.enabled||!saved.cred)return;var btn=document.getElementById('passkeyLoginButton');if(btn)btn.disabled=true;setMessage('Usando huella / Face ID…');try{var o=json(await post('passkey-auth-options',{user_id:saved.user||null,credential_id:saved.cred||null}));var pk=json(o.publicKey||o);if(pk.challenge)pk.challenge=from64(pk.challenge);if(Array.isArray(pk.allowCredentials))pk.allowCredentials=pk.allowCredentials.map(function(x){var y=Object.assign({},x);if(typeof y.id==='string')y.id=from64(y.id);return y});var a=await Promise.race([navigator.credentials.get({publicKey:pk}),new Promise(function(_,rej){setTimeout(function(){rej(new Error('TIMEOUT'))},8000)})]);var resp={id:a.id,rawId:b64url(a.rawId),type:a.type,response:{clientDataJSON:b64url(a.response.clientDataJSON),authenticatorData:b64url(a.response.authenticatorData),signature:b64url(a.response.signature),userHandle:a.response.userHandle?b64url(a.response.userHandle):null}};var v=json(await post('passkey-auth-verify',{response:resp,credential_id:a.id}));if(!v.user)throw new Error(v.error||'No autorizado');try{sessionStorage.setItem('hn_profile',JSON.stringify(v.user))}catch(_){}save({user:v.user.id,credentialId:a.id});location.reload()}catch(e){if(e&&e.name==='NotAllowedError'){setMessage('Biometría cancelada. Usa el acceso normal.')}else if(e&&e.message==='TIMEOUT'){setMessage('El acceso tardó demasiado. Usa el acceso normal.')}else{setMessage('No se pudo usar la Passkey. Usa el acceso normal.')}}finally{if(btn)btn.disabled=false}}
function render(){if(!supported())return;var saved=getSaved(),area=document.querySelector('.login-area');if(!area||!saved.enabled||!saved.cred)return;if(document.getElementById('passkeyLoginButton'))return;var b=document.createElement('button');b.id='passkeyLoginButton';b.type='button';b.className='login-button';b.style.marginTop='10px';b.textContent='🔐 ENTRAR CON HUELLA / FACE ID';b.addEventListener('click',login);area.appendChild(b)}
function init(){if(sessionStorage.getItem('hn_profile'))return;setTimeout(render,300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.HNPasskey={supported:supported,login:login,clear:clear,status:getSaved};
})();
