(function(){
'use strict';
var client=null,clientPromise=null,channel=null,started=false,songs=[],module=null,subtitle=null,badge=null,seenKey='hn_repertoire_seen_v1',historyArmed=false,previousScreen=null,videoWasMuted=true,ready=false;
var SUPABASE_URL='https://xzfradccsxonmauinecl.supabase.co';
var SUPABASE_KEY='sb_publishable_Ip5rGK0UVXIfOjs_RQ_LhA_c14foHN9';
function logged(){return !!sessionStorage.getItem('hn_profile')}
function getClient(){
  if(client&&typeof client.channel==='function')return Promise.resolve(client);
  if(window.hnSupabase&&typeof window.hnSupabase.channel==='function'){client=window.hnSupabase;return Promise.resolve(client)}
  if(!clientPromise){clientPromise=import('https://esm.sh/@supabase/supabase-js@2').then(function(m){client=m.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});return client})}
  return clientPromise;
}
function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function esc(v){var n=document.createElement('div');n.textContent=String(v==null?'':v);return n.innerHTML}
function externalUrl(v){v=String(v||'').trim();return /^https?:\/\//i.test(v)?v:''}
function seen(){try{var x=JSON.parse(localStorage.getItem(seenKey)||'[]');return Array.isArray(x)?x:[]}catch(_){return[]}}
function setSeen(x){try{localStorage.setItem(seenKey,JSON.stringify(x))}catch(_){}}
function markSeen(){setSeen(songs.map(function(x){return String(x.id)}));update()}
function find(){if(module&&document.body.contains(module))return module;module=null;subtitle=null;badge=null;document.querySelectorAll('.module').forEach(function(m){var t=m.querySelector('.module-title');if(t&&t.textContent.trim().toUpperCase()==='REPERTORIO'){module=m;subtitle=m.querySelector('.module-subtitle');module.style.position='relative';badge=m.querySelector('.hn-rep-badge');if(!badge){badge=el('span','hn-rep-badge');badge.setAttribute('aria-label','Nuevas canciones en repertorio');module.appendChild(badge)}}});return module}
function update(){find();if(subtitle)subtitle.textContent=ready?(songs.length?songs.length+' canciones':'Sin canciones'):'Cargando repertorio';var seenIds=seen(),unseen=songs.filter(function(x){return seenIds.indexOf(String(x.id))<0});if(badge){badge.textContent=unseen.length>99?'99+':String(unseen.length);badge.classList.toggle('hn-rep-badge-visible',unseen.length>0)}}
function style(){if(document.getElementById('hnRepertoireStyle'))return;var s=document.createElement('style');s.id='hnRepertoireStyle';s.textContent='.hn-rep-screen{height:100%!important;max-height:100%;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;box-sizing:border-box;padding-bottom:110px!important}.hn-rep-screen .hn-r-head{margin-top:24px;padding:0 0 18px;border-bottom:1px solid rgba(229,189,98,.25);font:14px Georgia,serif;letter-spacing:.18em;color:#fff1a8;text-transform:uppercase}.hn-rep-screen .hn-r-category{margin-top:24px;padding:0 0 8px;color:#e5bd62;font-size:9px;letter-spacing:.22em;text-transform:uppercase;border-bottom:1px solid rgba(229,189,98,.16)}.hn-rep-screen .hn-r-song{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid rgba(255,255,255,.08)}.hn-rep-screen .hn-r-info{min-width:0;flex:1}.hn-rep-screen .hn-r-title{color:#f4f1e8;font-size:12px;line-height:1.25;letter-spacing:.08em;text-transform:uppercase}.hn-rep-screen .hn-r-artist{margin-top:4px;color:rgba(244,241,232,.52);font-size:10px;line-height:1.25;letter-spacing:.06em}.hn-rep-screen .hn-r-reference{display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto;margin:0;padding:9px 10px;border:1px solid rgba(229,189,98,.62);color:#fff1a8;text-decoration:none;text-align:center;font-size:8px;line-height:1;letter-spacing:.13em;text-transform:uppercase;background:rgba(0,0,0,.24);white-space:nowrap}.hn-rep-screen .hn-r-empty{padding:34px 0;color:rgba(244,241,232,.42);font-size:10px;letter-spacing:.12em;text-transform:uppercase;text-align:center}.hn-rep-badge{position:absolute;top:10px;right:12px;min-width:24px;height:24px;padding:0 7px;border:1px solid #fff1a8;border-radius:999px;background:#e5bd62;color:#020302;display:none;align-items:center;justify-content:center;font:600 11px Arial,sans-serif;z-index:3}.hn-rep-badge.hn-rep-badge-visible{display:flex}.hn-r-back,.hn-r-back-top{display:block;margin:16px 0;position:relative;z-index:5;pointer-events:auto}@media(max-width:380px){.hn-rep-screen .hn-r-song{gap:8px}.hn-rep-screen .hn-r-reference{padding:8px 8px;font-size:7px;letter-spacing:.1em}}';document.head.appendChild(s)}
function close(fromButton){var screen=document.getElementById('moduleScreen');if(!screen)return;screen.classList.remove('is-active');if(previousScreen)previousScreen.classList.add('is-active');else document.getElementById('homeScreen')?.classList.add('is-active');var video=document.getElementById('backgroundVideo');if(video)video.muted=videoWasMuted;if(historyArmed&&fromButton){historyArmed=false;try{history.back()}catch(_){}}else if(!fromButton)historyArmed=false}
function render(){var screen=document.getElementById('moduleScreen');if(!screen)return;var inner=screen.querySelector('.screen-inner');if(!inner)return;inner.className='screen-inner coming-screen hn-rep-screen';inner.innerHTML='';inner.appendChild(el('p','brand metallic-gold','HAVANA NICE'));inner.appendChild(el('div','brand-line'));inner.appendChild(el('div','hn-r-head','Repertorio'));var top=el('button','back-button hn-r-back-top','Volver');top.type='button';top.onclick=function(e){e.preventDefault();e.stopPropagation();close(true)};inner.appendChild(top);if(!ready){inner.appendChild(el('div','hn-r-empty','Cargando repertorio'));return}var groups={ENGLISH:[],'ESPAÑOL':[]};songs.forEach(function(song){var c=String(song.category||'').trim().toUpperCase();var lang=(c==='ESPAÑOL'||c==='SPANISH'||c==='ES')?'ESPAÑOL':'ENGLISH';groups[lang].push(song)});['ENGLISH','ESPAÑOL'].forEach(function(cat){if(!groups[cat].length)return;inner.appendChild(el('div','hn-r-category',cat));groups[cat].forEach(function(song){var item=el('article','hn-r-song'),href=externalUrl(song.reference_url);item.innerHTML='<div class="hn-r-info"><div class="hn-r-title">'+esc(song.title||'')+'</div>'+(song.artist?'<div class="hn-r-artist">'+esc(song.artist)+'</div>':'')+'</div>'+(href?'<a class="hn-r-reference" href="'+esc(href)+'" target="_blank" rel="noopener noreferrer">REVISAR LINK ↗</a>':'');inner.appendChild(item)})});if(!groups.ENGLISH.length&&!groups['ESPAÑOL'].length)inner.appendChild(el('div','hn-r-empty','No hay canciones disponibles'));var back=el('button','back-button hn-r-back','Volver');back.type='button';back.onclick=function(e){e.preventDefault();e.stopPropagation();close(true)};inner.appendChild(back)}
function open(fromPop){if(!logged())return;previousScreen=document.querySelector('.screen.is-active:not(#moduleScreen)')||document.getElementById('homeScreen');render();if(ready)markSeen();var screen=document.getElementById('moduleScreen'),home=document.getElementById('homeScreen'),login=document.getElementById('loginScreen'),legacy=document.getElementById('repertoireScreen');if(login)login.classList.remove('is-active');document.querySelectorAll('.screen').forEach(function(s){if(s!==screen)s.classList.remove('is-active')});if(home)home.classList.remove('is-active');if(legacy)legacy.classList.remove('is-active');if(screen)screen.classList.add('is-active');var video=document.getElementById('backgroundVideo');if(video){videoWasMuted=!!video.muted;video.muted=true;video.play().catch(function(){})}if(!fromPop&&!historyArmed){try{history.pushState(Object.assign({},history.state||{},{hnRepertoire:true}),'',location.href);historyArmed=true}catch(_){}}}
async function sync(showFlash){if(!client||!logged())return;try{var r=await client.from('repertoire_songs').select('id,title,artist,category,position,active,reference_url,updated_at').eq('active',true).order('position',{ascending:true}).order('title',{ascending:true});if(r.error){console.error('[HN-Repertoire]',r.error);return}var next=r.data||[],oldIds=songs.map(function(x){return String(x.id)});var newSongs=next.filter(function(x){return oldIds.indexOf(String(x.id))<0});songs=next;ready=true;update();var screen=document.getElementById('moduleScreen');if(screen&&screen.classList.contains('is-active')&&screen.querySelector('.hn-rep-screen'))render();if(showFlash&&newSongs.length&&module){module.classList.remove('hn-rep-flash');void module.offsetWidth;module.classList.add('hn-rep-flash')}}catch(e){console.error('[HN-Repertoire]',e)}}
function subscribe(){if(!client)return;if(channel)try{client.removeChannel(channel)}catch(_){}channel=client.channel('hn-repertoire-realtime').on('postgres_changes',{event:'*',schema:'public',table:'repertoire_songs'},function(){sync(true)}).subscribe(function(status){if(status==='SUBSCRIBED')sync(false)})}
async function start(){if(started||!logged())return;try{client=await getClient()}catch(e){console.error('[HN-Repertoire] client init',e);return}if(!logged()||started)return;started=true;ready=false;update();await sync(false);subscribe()}
function stop(){started=false;ready=false;if(channel)try{client.removeChannel(channel)}catch(_){}channel=null;songs=[];update()}
function init(){style();find();if(module&&!module.dataset.hnRepBound){module.dataset.hnRepBound='1';module.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();if(typeof window.playClickSound==='function')try{window.playClickSound()}catch(_){}open(false)},true)};start();window.addEventListener('hn:session-ready',function(){start()});window.addEventListener('hn:session-logout',function(){stop()});window.addEventListener('online',function(){if(started)sync(false)});document.addEventListener('visibilitychange',function(){if(!document.hidden&&started)sync(false)});window.addEventListener('popstate',function(){var s=document.getElementById('moduleScreen');if(s&&s.classList.contains('is-active')&&s.querySelector('.hn-rep-screen'))close(false)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
