const CACHE='hn-v40';
const APP_SHELL=new Request('./index.html');
const SUPABASE_CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const SUPABASE_ESM='https://esm.sh/@supabase/supabase-js@2';
const IS_IOS=/iPad|iPhone|iPod/.test(self.navigator?.userAgent||'')||((self.navigator?.platform||'')==='MacIntel'&&(self.navigator?.maxTouchPoints||0)>1);
const FAMILY_IOS_VERSION='ios-family-20260918-1835';
async function normalizeAppShell(response){if(!response||!response.ok)return response;const text=await response.text();let fixed=text.split(SUPABASE_CDN).join(SUPABASE_ESM);if(IS_IOS)fixed=fixed.replace(/\.\/family-v1\.js\?v=[^"']+/g,'./family-v1.js?v='+FAMILY_IOS_VERSION);const headers=new Headers(response.headers);headers.delete('content-encoding');headers.delete('content-length');headers.set('content-type','text/html; charset=utf-8');headers.set('cache-control','no-store');return new Response(fixed,{status:response.status,statusText:response.statusText,headers})}
async function updateAppShell(){try{const response=await fetch('./index.html',{cache:'no-store'});if(!response.ok)return;const fixed=await normalizeAppShell(response);const cache=await caches.open(CACHE);await cache.put(APP_SHELL,fixed.clone())}catch(_){}}
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(updateAppShell())});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const u=new URL(event.request.url);if(u.hostname==='cdn.jsdelivr.net'&&u.pathname==='/npm/@supabase/supabase-js@2/+esm'){event.respondWith(fetch(SUPABASE_ESM).catch(()=>fetch(event.request)));return}if(event.request.mode==='navigate'&&u.origin===self.location.origin){event.respondWith((async()=>{const cache=await caches.open(CACHE);const cached=await cache.match(APP_SHELL);if(cached){try{const response=await fetch(event.request,{cache:'no-store'});const fixed=await normalizeAppShell(response);await cache.put(APP_SHELL,fixed.clone());return fixed}catch(_){return cached}}try{const response=await fetch(event.request,{cache:'no-store'});const fixed=await normalizeAppShell(response);await cache.put(APP_SHELL,fixed.clone());return fixed}catch(_){return cached||Response.error()}})());return}if(IS_IOS&&u.pathname.endsWith('/family-v1.js')){const fresh=new URL(event.request.url);fresh.searchParams.set('hn_ios_family',FAMILY_IOS_VERSION);event.respondWith(fetch(new Request(fresh.toString(),{method:'GET',credentials:'same-origin',cache:'no-store'})).catch(()=>fetch(event.request,{cache:'reload'})));return}if(u.pathname.endsWith('/notifications-v5.js')||u.pathname.endsWith('/operations-fix.js')||u.pathname.endsWith('/ios-install-v1.js')||u.pathname.endsWith('/chat-media-fix-v1.js')||u.pathname.endsWith('/chat-v2.js')||u.pathname.endsWith('/chat-typing-v2.js')||u.pathname.endsWith('/chat-realtime-guard-v1.js')||u.pathname.endsWith('/chat-keyboard-v1.js')||u.pathname.endsWith('/chat-media-lightbox-v2.js')||u.pathname.endsWith('/chat-video-controls-v1.js')||u.pathname.endsWith('/family-v1.js')||u.pathname.endsWith('/musician-device-access-v1.js')||u.pathname.endsWith('/musician-push.js')||u.pathname.endsWith('/musician-background-v1.js')||u.pathname.endsWith('/calendar-v1.js')||u.pathname.endsWith('/calendar-expand.js')||u.pathname.endsWith('/calendar-navigation.js')||u.pathname.endsWith('/calendar-recipients-v1.js')||u.pathname.endsWith('/repertoire-v1.js')||u.pathname.endsWith('/notifications-navigation.js')){event.respondWith(fetch(event.request,{cache:'no-store'}).catch(()=>caches.match(event.request)));return}event.respondWith(fetch(event.request).catch(()=>caches.match(event.request)))});
self.addEventListener('push',event=>{event.waitUntil((async()=>{let d={};try{d=event.data?event.data.json():{}}catch(_){d={}}const title=d.title||'HAVANA NICE',body=d.message||'Nueva actualización',url=d.url||'/';let n=1;try{n=(await new Promise(resolve=>{const r=indexedDB.open('hn_push',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>{const q=r.result.transaction('state','readwrite').objectStore('state').get('count');q.onsuccess=()=>resolve(Number(q.result||0));q.onerror=()=>resolve(0)};r.onerror=()=>resolve(0)}))+1}catch(_){}try{const r=indexedDB.open('hn_push',1);r.onsuccess=()=>{const db=r.result;db.transaction('state','readwrite').objectStore('state').put(n,'count')}}catch(_){}try{if(self.navigator&&self.navigator.setAppBadge)await self.navigator.setAppBadge(Math.min(99,n))}catch(_){}await self.registration.showNotification(title,{body,tag:'hn-push-'+Date.now(),renotify:true,silent:false,vibrate:[200,100,200,100,300],data:{url}})})())});
self.addEventListener('notificationclick',event=>{event.notification.close();const url=(event.notification.data&&event.notification.data.url)||'/';event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const c of list){if('focus'in c)return c.focus()}return clients.openWindow(url)}))});
